// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/machine/api/pb/docker.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ContainerType specifies the purpose of the container being created.
type CreateServiceContainerRequest_ContainerType int32

const (
	// SERVICE is the default type for long-running service containers.
	CreateServiceContainerRequest_SERVICE CreateServiceContainerRequest_ContainerType = 0
	// PRE_DEPLOY is a one-shot container for a pre-deploy hook to run before service deployment.
	CreateServiceContainerRequest_PRE_DEPLOY CreateServiceContainerRequest_ContainerType = 1
)

// Enum value maps for CreateServiceContainerRequest_ContainerType.
var (
	CreateServiceContainerRequest_ContainerType_name = map[int32]string{
		0: "SERVICE",
		1: "PRE_DEPLOY",
	}
	CreateServiceContainerRequest_ContainerType_value = map[string]int32{
		"SERVICE":    0,
		"PRE_DEPLOY": 1,
	}
)

func (x CreateServiceContainerRequest_ContainerType) Enum() *CreateServiceContainerRequest_ContainerType {
	p := new(CreateServiceContainerRequest_ContainerType)
	*p = x
	return p
}

func (x CreateServiceContainerRequest_ContainerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateServiceContainerRequest_ContainerType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_machine_api_pb_docker_proto_enumTypes[0].Descriptor()
}

func (CreateServiceContainerRequest_ContainerType) Type() protoreflect.EnumType {
	return &file_internal_machine_api_pb_docker_proto_enumTypes[0]
}

func (x CreateServiceContainerRequest_ContainerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateServiceContainerRequest_ContainerType.Descriptor instead.
func (CreateServiceContainerRequest_ContainerType) EnumDescriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_docker_proto_rawDescGZIP(), []int{31, 0}
}

type CreateContainerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON serialised container.Config.
	Config []byte `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// JSON serialised container.HostConfig.
	HostConfig []byte `protobuf:"bytes,2,opt,name=host_config,json=hostConfig,proto3" json:"host_config,omitempty"`
	// JSON serialised network.NetworkingConfig.
	NetworkConfig []byte `protobuf:"bytes,3,opt,name=network_config,json=networkConfig,proto3" json:"network_config,omitempty"`
	// JSON serialised ocispec.Platform.
	Platform      []byte `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	Name          string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContainerRequest) Reset() {
	*x = CreateContainerRequest{}
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContainerRequest) ProtoMessage() {}

func (x *CreateContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContainerRequest.ProtoReflect.Descriptor instead.
func (*CreateContainerRequest) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_docker_proto_rawDescGZIP(), []int{0}
}

func (x *CreateContainerRequest) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CreateContainerRequest) GetHostConfig() []byte {
	if x != nil {
		return x.HostConfig
	}
	return nil
}

func (x *CreateContainerRequest) GetNetworkConfig() []byte {
	if x != nil {
		return x.NetworkConfig
	}
	return nil
}

func (x *CreateContainerRequest) GetPlatform() []byte {
	if x != nil {
		return x.Platform
	}
	return nil
}

func (x *CreateContainerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateContainerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON serialised container.CreateResponse.
	Response      []byte `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContainerResponse) Reset() {
	*x = CreateContainerResponse{}
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContainerResponse) ProtoMessage() {}

func (x *CreateContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContainerResponse.ProtoReflect.Descriptor instead.
func (*CreateContainerResponse) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_docker_proto_rawDescGZIP(), []int{1}
}

func (x *CreateContainerResponse) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

type InspectContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectContainerRequest) Reset() {
	*x = InspectContainerRequest{}
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectContainerRequest) ProtoMessage() {}

func (x *InspectContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectContainerRequest.ProtoReflect.Descriptor instead.
func (*InspectContainerRequest) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_docker_proto_rawDescGZIP(), []int{2}
}

func (x *InspectContainerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type InspectContainerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON serialised container.InspectResponse.
	Response      []byte `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectContainerResponse) Reset() {
	*x = InspectContainerResponse{}
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectContainerResponse) ProtoMessage() {}

func (x *InspectContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectContainerResponse.ProtoReflect.Descriptor instead.
func (*InspectContainerResponse) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_docker_proto_rawDescGZIP(), []int{3}
}

func (x *InspectContainerResponse) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

type StartContainerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// JSON serialised container.StartOptions.
	Options       []byte `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartContainerRequest) Reset() {
	*x = StartContainerRequest{}
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartContainerRequest) ProtoMessage() {}

func (x *StartContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartContainerRequest.ProtoReflect.Descriptor instead.
func (*StartContainerRequest) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_docker_proto_rawDescGZIP(), []int{4}
}

func (x *StartContainerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StartContainerRequest) GetOptions() []byte {
	if x != nil {
		return x.Options
	}
	return nil
}

type StopContainerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// JSON serialised container.StopOptions.
	Options       []byte `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopContainerRequest) Reset() {
	*x = StopContainerRequest{}
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopContainerRequest) ProtoMessage() {}

func (x *StopContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopContainerRequest.ProtoReflect.Descriptor instead.
func (*StopContainerRequest) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_docker_proto_rawDescGZIP(), []int{5}
}

func (x *StopContainerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StopContainerRequest) GetOptions() []byte {
	if x != nil {
		return x.Options
	}
	return nil
}

type ListContainersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON serialised container.ListOptions.
	Options       []byte `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContainersRequest) Reset() {
	*x = ListContainersRequest{}
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContainersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContainersRequest) ProtoMessage() {}

func (x *ListContainersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContainersRequest.ProtoReflect.Descriptor instead.
func (*ListContainersRequest) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_docker_proto_rawDescGZIP(), []int{6}
}

func (x *ListContainersRequest) GetOptions() []byte {
	if x != nil {
		return x.Options
	}
	return nil
}

type ListContainersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Must contain only one repeated messages field to allow broadcasting ListContainers requests to multiple machines.
	Messages      []*MachineContainers `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContainersResponse) Reset() {
	*x = ListContainersResponse{}
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContainersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContainersResponse) ProtoMessage() {}

func (x *ListContainersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContainersResponse.ProtoReflect.Descriptor instead.
func (*ListContainersResponse) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_docker_proto_rawDescGZIP(), []int{7}
}

func (x *ListContainersResponse) GetMessages() []*MachineContainers {
	if x != nil {
		return x.Messages
	}
	return nil
}

type MachineContainers struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Metadata *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// JSON serialised []container.InspectResponse.
	Containers    []byte `protobuf:"bytes,2,opt,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineContainers) Reset() {
	*x = MachineContainers{}
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineContainers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineContainers) ProtoMessage() {}

func (x *MachineContainers) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineContainers.ProtoReflect.Descriptor instead.
func (*MachineContainers) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_docker_proto_rawDescGZIP(), []int{8}
}

func (x *MachineContainers) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MachineContainers) GetContainers() []byte {
	if x != nil {
		return x.Containers
	}
	return nil
}

type RemoveContainerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// JSON serialised container.RemoveOptions.
	Options       []byte `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveContainerRequest) Reset() {
	*x = RemoveContainerRequest{}
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveContainerRequest) ProtoMessage() {}

func (x *RemoveContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveContainerRequest.ProtoReflect.Descriptor instead.
func (*RemoveContainerRequest) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_docker_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveContainerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RemoveContainerRequest) GetOptions() []byte {
	if x != nil {
		return x.Options
	}
	return nil
}

type ExecContainerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ExecContainerRequest_Config
	//	*ExecContainerRequest_Stdin
	//	*ExecContainerRequest_Resize
	Payload       isExecContainerRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecContainerRequest) Reset() {
	*x = ExecContainerRequest{}
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecContainerRequest) ProtoMessage() {}

func (x *ExecContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecContainerRequest.ProtoReflect.Descriptor instead.
func (*ExecContainerRequest) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_docker_proto_rawDescGZIP(), []int{10}
}

func (x *ExecContainerRequest) GetPayload() isExecContainerRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecContainerRequest) GetConfig() *ExecConfig {
	if x != nil {
		if x, ok := x.Payload.(*ExecContainerRequest_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *ExecContainerRequest) GetStdin() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ExecContainerRequest_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *ExecContainerRequest) GetResize() *ResizeEvent {
	if x != nil {
		if x, ok := x.Payload.(*ExecContainerRequest_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

type isExecContainerRequest_Payload interface {
	isExecContainerRequest_Payload()
}

type ExecContainerRequest_Config struct {
	// Initial configuration for the exec session. Must be sent as the first message.
	Config *ExecConfig `protobuf:"bytes,1,opt,name=config,proto3,oneof"`
}

type ExecContainerRequest_Stdin struct {
	// Raw stdin data to be written to the exec process.
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

type ExecContainerRequest_Resize struct {
	// TTY resize event (only used when TTY is enabled).
	Resize *ResizeEvent `protobuf:"bytes,3,opt,name=resize,proto3,oneof"`
}

func (*ExecContainerRequest_Config) isExecContainerRequest_Payload() {}

func (*ExecContainerRequest_Stdin) isExecContainerRequest_Payload() {}

func (*ExecContainerRequest_Resize) isExecContainerRequest_Payload() {}

type ExecConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container ID to execute the command in.
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// JSON serialised ExecOptions
	Options       []byte `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecConfig) Reset() {
	*x = ExecConfig{}
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecConfig) ProtoMessage() {}

func (x *ExecConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecConfig.ProtoReflect.Descriptor instead.
func (*ExecConfig) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_docker_proto_rawDescGZIP(), []int{11}
}

func (x *ExecConfig) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ExecConfig) GetOptions() []byte {
	if x != nil {
		return x.Options
	}
	return nil
}

type ResizeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint32                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Width         uint32                 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeEvent) Reset() {
	*x = ResizeEvent{}
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeEvent) ProtoMessage() {}

func (x *ResizeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeEvent.ProtoReflect.Descriptor instead.
func (*ResizeEvent) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_docker_proto_rawDescGZIP(), []int{12}
}

func (x *ResizeEvent) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ResizeEvent) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

type ExecContainerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ExecContainerResponse_ExecId
	//	*ExecContainerResponse_Stdout
	//	*ExecContainerResponse_Stderr
	//	*ExecContainerResponse_ExitCode
	Payload       isExecContainerResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecContainerResponse) Reset() {
	*x = ExecContainerResponse{}
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecContainerResponse) ProtoMessage() {}

func (x *ExecContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecContainerResponse.ProtoReflect.Descriptor instead.
func (*ExecContainerResponse) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_docker_proto_rawDescGZIP(), []int{13}
}

func (x *ExecContainerResponse) GetPayload() isExecContainerResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecContainerResponse) GetExecId() string {
	if x != nil {
		if x, ok := x.Payload.(*ExecContainerResponse_ExecId); ok {
			return x.ExecId
		}
	}
	return ""
}

func (x *ExecContainerResponse) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ExecContainerResponse_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ExecContainerResponse) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ExecContainerResponse_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *ExecContainerResponse) GetExitCode() int32 {
	if x != nil {
		if x, ok := x.Payload.(*ExecContainerResponse_ExitCode); ok {
			return x.ExitCode
		}
	}
	return 0
}

type isExecContainerResponse_Payload interface {
	isExecContainerResponse_Payload()
}

type ExecContainerResponse_ExecId struct {
	// Exec instance ID returned after creating the exec.
	ExecId string `protobuf:"bytes,1,opt,name=exec_id,json=execId,proto3,oneof"`
}

type ExecContainerResponse_Stdout struct {
	// Raw stdout data from the exec process.
	Stdout []byte `protobuf:"bytes,2,opt,name=stdout,proto3,oneof"`
}

type ExecContainerResponse_Stderr struct {
	// Raw stderr data from the exec process (only when TTY is disabled).
	Stderr []byte `protobuf:"bytes,3,opt,name=stderr,proto3,oneof"`
}

type ExecContainerResponse_ExitCode struct {
	// Exit code of the exec process. Sent as the final message.
	ExitCode int32 `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3,oneof"`
}

func (*ExecContainerResponse_ExecId) isExecContainerResponse_Payload() {}

func (*ExecContainerResponse_Stdout) isExecContainerResponse_Payload() {}

func (*ExecContainerResponse_Stderr) isExecContainerResponse_Payload() {}

func (*ExecContainerResponse_ExitCode) isExecContainerResponse_Payload() {}

type PullImageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Image string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	// JSON serialised image.PullOptions.
	Options       []byte `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullImageRequest) Reset() {
	*x = PullImageRequest{}
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullImageRequest) ProtoMessage() {}

func (x *PullImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullImageRequest.ProtoReflect.Descriptor instead.
func (*PullImageRequest) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_docker_proto_rawDescGZIP(), []int{14}
}

func (x *PullImageRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *PullImageRequest) GetOptions() []byte {
	if x != nil {
		return x.Options
	}
	return nil
}

type JSONMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON serialised jsonmessage.JSONMessage.
	Message       []byte `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JSONMessage) Reset() {
	*x = JSONMessage{}
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JSONMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONMessage) ProtoMessage() {}

func (x *JSONMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONMessage.ProtoReflect.Descriptor instead.
func (*JSONMessage) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_docker_proto_rawDescGZIP(), []int{15}
}

func (x *JSONMessage) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type InspectImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectImageRequest) Reset() {
	*x = InspectImageRequest{}
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectImageRequest) ProtoMessage() {}

func (x *InspectImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectImageRequest.ProtoReflect.Descriptor instead.
func (*InspectImageRequest) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_docker_proto_rawDescGZIP(), []int{16}
}

func (x *InspectImageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type InspectImageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Must contain only one repeated messages field to allow broadcasting InspectImage requests to multiple machines.
	Messages      []*Image `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectImageResponse) Reset() {
	*x = InspectImageResponse{}
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectImageResponse) ProtoMessage() {}

func (x *InspectImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectImageResponse.ProtoReflect.Descriptor instead.
func (*InspectImageResponse) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_docker_proto_rawDescGZIP(), []int{17}
}

func (x *InspectImageResponse) GetMessages() []*Image {
	if x != nil {
		return x.Messages
	}
	return nil
}

type Image struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Metadata *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// JSON serialised image.InspectResponse.
	Image         []byte `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_docker_proto_rawDescGZIP(), []int{18}
}

func (x *Image) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Image) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

type InspectRemoteImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectRemoteImageRequest) Reset() {
	*x = InspectRemoteImageRequest{}
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectRemoteImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectRemoteImageRequest) ProtoMessage() {}

func (x *InspectRemoteImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectRemoteImageRequest.ProtoReflect.Descriptor instead.
func (*InspectRemoteImageRequest) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_docker_proto_rawDescGZIP(), []int{19}
}

func (x *InspectRemoteImageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type InspectRemoteImageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Must contain only one repeated messages field to allow broadcasting InspectRemoteImage requests to multiple machines.
	Messages      []*RemoteImage `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectRemoteImageResponse) Reset() {
	*x = InspectRemoteImageResponse{}
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectRemoteImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectRemoteImageResponse) ProtoMessage() {}

func (x *InspectRemoteImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectRemoteImageResponse.ProtoReflect.Descriptor instead.
func (*InspectRemoteImageResponse) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_docker_proto_rawDescGZIP(), []int{20}
}

func (x *InspectRemoteImageResponse) GetMessages() []*RemoteImage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type RemoteImage struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Metadata *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Image reference in the canonical form with the digest.
	Reference string `protobuf:"bytes,2,opt,name=reference,proto3" json:"reference,omitempty"`
	// Raw JSON manifest from the registry.
	Manifest      []byte `protobuf:"bytes,3,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoteImage) Reset() {
	*x = RemoteImage{}
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteImage) ProtoMessage() {}

func (x *RemoteImage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteImage.ProtoReflect.Descriptor instead.
func (*RemoteImage) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_docker_proto_rawDescGZIP(), []int{21}
}

func (x *RemoteImage) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RemoteImage) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *RemoteImage) GetManifest() []byte {
	if x != nil {
		return x.Manifest
	}
	return nil
}

type ListImagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON serialised image.ListOptions.
	Options       []byte `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImagesRequest) Reset() {
	*x = ListImagesRequest{}
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImagesRequest) ProtoMessage() {}

func (x *ListImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImagesRequest.ProtoReflect.Descriptor instead.
func (*ListImagesRequest) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_docker_proto_rawDescGZIP(), []int{22}
}

func (x *ListImagesRequest) GetOptions() []byte {
	if x != nil {
		return x.Options
	}
	return nil
}

type ListImagesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Must contain only one repeated messages field to allow broadcasting ListImages requests to multiple machines.
	Messages      []*MachineImages `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImagesResponse) Reset() {
	*x = ListImagesResponse{}
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImagesResponse) ProtoMessage() {}

func (x *ListImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImagesResponse.ProtoReflect.Descriptor instead.
func (*ListImagesResponse) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_docker_proto_rawDescGZIP(), []int{23}
}

func (x *ListImagesResponse) GetMessages() []*MachineImages {
	if x != nil {
		return x.Messages
	}
	return nil
}

type MachineImages struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Metadata *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// JSON serialised []image.Summary.
	Images []byte `protobuf:"bytes,2,opt,name=images,proto3" json:"images,omitempty"`
	// True if Docker uses the containerd image store, false if it uses its internal image store.
	ContainerdStore bool `protobuf:"varint,3,opt,name=containerd_store,json=containerdStore,proto3" json:"containerd_store,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MachineImages) Reset() {
	*x = MachineImages{}
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineImages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineImages) ProtoMessage() {}

func (x *MachineImages) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineImages.ProtoReflect.Descriptor instead.
func (*MachineImages) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_docker_proto_rawDescGZIP(), []int{24}
}

func (x *MachineImages) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MachineImages) GetImages() []byte {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *MachineImages) GetContainerdStore() bool {
	if x != nil {
		return x.ContainerdStore
	}
	return false
}

type CreateVolumeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON serialised volume.CreateOptions.
	Options       []byte `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVolumeRequest) Reset() {
	*x = CreateVolumeRequest{}
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVolumeRequest) ProtoMessage() {}

func (x *CreateVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVolumeRequest.ProtoReflect.Descriptor instead.
func (*CreateVolumeRequest) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_docker_proto_rawDescGZIP(), []int{25}
}

func (x *CreateVolumeRequest) GetOptions() []byte {
	if x != nil {
		return x.Options
	}
	return nil
}

type CreateVolumeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON serialised volume.Volume.
	Volume        []byte `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVolumeResponse) Reset() {
	*x = CreateVolumeResponse{}
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVolumeResponse) ProtoMessage() {}

func (x *CreateVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVolumeResponse.ProtoReflect.Descriptor instead.
func (*CreateVolumeResponse) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_docker_proto_rawDescGZIP(), []int{26}
}

func (x *CreateVolumeResponse) GetVolume() []byte {
	if x != nil {
		return x.Volume
	}
	return nil
}

type ListVolumesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON serialised volume.ListOptions.
	Options       []byte `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVolumesRequest) Reset() {
	*x = ListVolumesRequest{}
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVolumesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVolumesRequest) ProtoMessage() {}

func (x *ListVolumesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVolumesRequest.ProtoReflect.Descriptor instead.
func (*ListVolumesRequest) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_docker_proto_rawDescGZIP(), []int{27}
}

func (x *ListVolumesRequest) GetOptions() []byte {
	if x != nil {
		return x.Options
	}
	return nil
}

type ListVolumesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Must contain only one repeated messages field to allow broadcasting ListVolumes requests to multiple machines.
	Messages      []*MachineVolumes `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVolumesResponse) Reset() {
	*x = ListVolumesResponse{}
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVolumesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVolumesResponse) ProtoMessage() {}

func (x *ListVolumesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVolumesResponse.ProtoReflect.Descriptor instead.
func (*ListVolumesResponse) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_docker_proto_rawDescGZIP(), []int{28}
}

func (x *ListVolumesResponse) GetMessages() []*MachineVolumes {
	if x != nil {
		return x.Messages
	}
	return nil
}

type MachineVolumes struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Metadata *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// JSON serialised volume.ListResponse.
	Response      []byte `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineVolumes) Reset() {
	*x = MachineVolumes{}
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineVolumes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineVolumes) ProtoMessage() {}

func (x *MachineVolumes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineVolumes.ProtoReflect.Descriptor instead.
func (*MachineVolumes) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_docker_proto_rawDescGZIP(), []int{29}
}

func (x *MachineVolumes) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MachineVolumes) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

type RemoveVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveVolumeRequest) Reset() {
	*x = RemoveVolumeRequest{}
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveVolumeRequest) ProtoMessage() {}

func (x *RemoveVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveVolumeRequest.ProtoReflect.Descriptor instead.
func (*RemoveVolumeRequest) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_docker_proto_rawDescGZIP(), []int{30}
}

func (x *RemoveVolumeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RemoveVolumeRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type CreateServiceContainerRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ServiceId string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	// JSON serialised api.ServiceSpec.
	ServiceSpec   []byte                                      `protobuf:"bytes,2,opt,name=service_spec,json=serviceSpec,proto3" json:"service_spec,omitempty"`
	ContainerName string                                      `protobuf:"bytes,3,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	ContainerType CreateServiceContainerRequest_ContainerType `protobuf:"varint,4,opt,name=container_type,json=containerType,proto3,enum=api.CreateServiceContainerRequest_ContainerType" json:"container_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServiceContainerRequest) Reset() {
	*x = CreateServiceContainerRequest{}
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceContainerRequest) ProtoMessage() {}

func (x *CreateServiceContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceContainerRequest.ProtoReflect.Descriptor instead.
func (*CreateServiceContainerRequest) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_docker_proto_rawDescGZIP(), []int{31}
}

func (x *CreateServiceContainerRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *CreateServiceContainerRequest) GetServiceSpec() []byte {
	if x != nil {
		return x.ServiceSpec
	}
	return nil
}

func (x *CreateServiceContainerRequest) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *CreateServiceContainerRequest) GetContainerType() CreateServiceContainerRequest_ContainerType {
	if x != nil {
		return x.ContainerType
	}
	return CreateServiceContainerRequest_SERVICE
}

type ServiceContainer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON serialised container.InspectResponse.
	Container []byte `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	// JSON serialised api.ServiceSpec.
	ServiceSpec   []byte `protobuf:"bytes,2,opt,name=service_spec,json=serviceSpec,proto3" json:"service_spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceContainer) Reset() {
	*x = ServiceContainer{}
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceContainer) ProtoMessage() {}

func (x *ServiceContainer) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceContainer.ProtoReflect.Descriptor instead.
func (*ServiceContainer) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_docker_proto_rawDescGZIP(), []int{32}
}

func (x *ServiceContainer) GetContainer() []byte {
	if x != nil {
		return x.Container
	}
	return nil
}

func (x *ServiceContainer) GetServiceSpec() []byte {
	if x != nil {
		return x.ServiceSpec
	}
	return nil
}

type ListServiceContainersRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ServiceId string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	// JSON serialised container.ListOptions.
	Options       []byte `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServiceContainersRequest) Reset() {
	*x = ListServiceContainersRequest{}
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServiceContainersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServiceContainersRequest) ProtoMessage() {}

func (x *ListServiceContainersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServiceContainersRequest.ProtoReflect.Descriptor instead.
func (*ListServiceContainersRequest) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_docker_proto_rawDescGZIP(), []int{33}
}

func (x *ListServiceContainersRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ListServiceContainersRequest) GetOptions() []byte {
	if x != nil {
		return x.Options
	}
	return nil
}

type ListServiceContainersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Must contain only one repeated messages field to allow broadcasting ListServiceContainers requests
	// to multiple machines.
	Messages      []*MachineServiceContainers `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServiceContainersResponse) Reset() {
	*x = ListServiceContainersResponse{}
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServiceContainersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServiceContainersResponse) ProtoMessage() {}

func (x *ListServiceContainersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServiceContainersResponse.ProtoReflect.Descriptor instead.
func (*ListServiceContainersResponse) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_docker_proto_rawDescGZIP(), []int{34}
}

func (x *ListServiceContainersResponse) GetMessages() []*MachineServiceContainers {
	if x != nil {
		return x.Messages
	}
	return nil
}

type MachineServiceContainers struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Metadata   *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Containers []*ServiceContainer    `protobuf:"bytes,2,rep,name=containers,proto3" json:"containers,omitempty"`
	// One-shot containers for deployment hooks (e.g. pre-deploy).
	HookContainers []*ServiceContainer `protobuf:"bytes,3,rep,name=hook_containers,json=hookContainers,proto3" json:"hook_containers,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MachineServiceContainers) Reset() {
	*x = MachineServiceContainers{}
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineServiceContainers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineServiceContainers) ProtoMessage() {}

func (x *MachineServiceContainers) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_docker_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineServiceContainers.ProtoReflect.Descriptor instead.
func (*MachineServiceContainers) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_docker_proto_rawDescGZIP(), []int{35}
}

func (x *MachineServiceContainers) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MachineServiceContainers) GetContainers() []*ServiceContainer {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *MachineServiceContainers) GetHookContainers() []*ServiceContainer {
	if x != nil {
		return x.HookContainers
	}
	return nil
}

var File_internal_machine_api_pb_docker_proto protoreflect.FileDescriptor

const file_internal_machine_api_pb_docker_proto_rawDesc = "" +
	"\n" +
	"$internal/machine/api/pb/docker.proto\x12\x03api\x1a\x1bgoogle/protobuf/empty.proto\x1a$internal/machine/api/pb/common.proto\"\xa8\x01\n" +
	"\x16CreateContainerRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\fR\x06config\x12\x1f\n" +
	"\vhost_config\x18\x02 \x01(\fR\n" +
	"hostConfig\x12%\n" +
	"\x0enetwork_config\x18\x03 \x01(\fR\rnetworkConfig\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\fR\bplatform\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\"5\n" +
	"\x17CreateContainerResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\fR\bresponse\")\n" +
	"\x17InspectContainerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"6\n" +
	"\x18InspectContainerResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\fR\bresponse\"A\n" +
	"\x15StartContainerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aoptions\x18\x02 \x01(\fR\aoptions\"@\n" +
	"\x14StopContainerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aoptions\x18\x02 \x01(\fR\aoptions\"1\n" +
	"\x15ListContainersRequest\x12\x18\n" +
	"\aoptions\x18\x01 \x01(\fR\aoptions\"L\n" +
	"\x16ListContainersResponse\x122\n" +
	"\bmessages\x18\x01 \x03(\v2\x16.api.MachineContainersR\bmessages\"^\n" +
	"\x11MachineContainers\x12)\n" +
	"\bmetadata\x18\x01 \x01(\v2\r.api.MetadataR\bmetadata\x12\x1e\n" +
	"\n" +
	"containers\x18\x02 \x01(\fR\n" +
	"containers\"B\n" +
	"\x16RemoveContainerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aoptions\x18\x02 \x01(\fR\aoptions\"\x90\x01\n" +
	"\x14ExecContainerRequest\x12)\n" +
	"\x06config\x18\x01 \x01(\v2\x0f.api.ExecConfigH\x00R\x06config\x12\x16\n" +
	"\x05stdin\x18\x02 \x01(\fH\x00R\x05stdin\x12*\n" +
	"\x06resize\x18\x03 \x01(\v2\x10.api.ResizeEventH\x00R\x06resizeB\t\n" +
	"\apayload\"I\n" +
	"\n" +
	"ExecConfig\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x18\n" +
	"\aoptions\x18\x02 \x01(\fR\aoptions\";\n" +
	"\vResizeEvent\x12\x16\n" +
	"\x06height\x18\x01 \x01(\rR\x06height\x12\x14\n" +
	"\x05width\x18\x02 \x01(\rR\x05width\"\x90\x01\n" +
	"\x15ExecContainerResponse\x12\x19\n" +
	"\aexec_id\x18\x01 \x01(\tH\x00R\x06execId\x12\x18\n" +
	"\x06stdout\x18\x02 \x01(\fH\x00R\x06stdout\x12\x18\n" +
	"\x06stderr\x18\x03 \x01(\fH\x00R\x06stderr\x12\x1d\n" +
	"\texit_code\x18\x04 \x01(\x05H\x00R\bexitCodeB\t\n" +
	"\apayload\"B\n" +
	"\x10PullImageRequest\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x18\n" +
	"\aoptions\x18\x02 \x01(\fR\aoptions\"'\n" +
	"\vJSONMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\fR\amessage\"%\n" +
	"\x13InspectImageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\">\n" +
	"\x14InspectImageResponse\x12&\n" +
	"\bmessages\x18\x01 \x03(\v2\n" +
	".api.ImageR\bmessages\"H\n" +
	"\x05Image\x12)\n" +
	"\bmetadata\x18\x01 \x01(\v2\r.api.MetadataR\bmetadata\x12\x14\n" +
	"\x05image\x18\x02 \x01(\fR\x05image\"+\n" +
	"\x19InspectRemoteImageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"J\n" +
	"\x1aInspectRemoteImageResponse\x12,\n" +
	"\bmessages\x18\x01 \x03(\v2\x10.api.RemoteImageR\bmessages\"r\n" +
	"\vRemoteImage\x12)\n" +
	"\bmetadata\x18\x01 \x01(\v2\r.api.MetadataR\bmetadata\x12\x1c\n" +
	"\treference\x18\x02 \x01(\tR\treference\x12\x1a\n" +
	"\bmanifest\x18\x03 \x01(\fR\bmanifest\"-\n" +
	"\x11ListImagesRequest\x12\x18\n" +
	"\aoptions\x18\x01 \x01(\fR\aoptions\"D\n" +
	"\x12ListImagesResponse\x12.\n" +
	"\bmessages\x18\x01 \x03(\v2\x12.api.MachineImagesR\bmessages\"}\n" +
	"\rMachineImages\x12)\n" +
	"\bmetadata\x18\x01 \x01(\v2\r.api.MetadataR\bmetadata\x12\x16\n" +
	"\x06images\x18\x02 \x01(\fR\x06images\x12)\n" +
	"\x10containerd_store\x18\x03 \x01(\bR\x0fcontainerdStore\"/\n" +
	"\x13CreateVolumeRequest\x12\x18\n" +
	"\aoptions\x18\x01 \x01(\fR\aoptions\".\n" +
	"\x14CreateVolumeResponse\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\fR\x06volume\".\n" +
	"\x12ListVolumesRequest\x12\x18\n" +
	"\aoptions\x18\x01 \x01(\fR\aoptions\"F\n" +
	"\x13ListVolumesResponse\x12/\n" +
	"\bmessages\x18\x01 \x03(\v2\x13.api.MachineVolumesR\bmessages\"W\n" +
	"\x0eMachineVolumes\x12)\n" +
	"\bmetadata\x18\x01 \x01(\v2\r.api.MetadataR\bmetadata\x12\x1a\n" +
	"\bresponse\x18\x02 \x01(\fR\bresponse\";\n" +
	"\x13RemoveVolumeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"\x8f\x02\n" +
	"\x1dCreateServiceContainerRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12!\n" +
	"\fservice_spec\x18\x02 \x01(\fR\vserviceSpec\x12%\n" +
	"\x0econtainer_name\x18\x03 \x01(\tR\rcontainerName\x12W\n" +
	"\x0econtainer_type\x18\x04 \x01(\x0e20.api.CreateServiceContainerRequest.ContainerTypeR\rcontainerType\",\n" +
	"\rContainerType\x12\v\n" +
	"\aSERVICE\x10\x00\x12\x0e\n" +
	"\n" +
	"PRE_DEPLOY\x10\x01\"S\n" +
	"\x10ServiceContainer\x12\x1c\n" +
	"\tcontainer\x18\x01 \x01(\fR\tcontainer\x12!\n" +
	"\fservice_spec\x18\x02 \x01(\fR\vserviceSpec\"W\n" +
	"\x1cListServiceContainersRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x18\n" +
	"\aoptions\x18\x02 \x01(\fR\aoptions\"Z\n" +
	"\x1dListServiceContainersResponse\x129\n" +
	"\bmessages\x18\x01 \x03(\v2\x1d.api.MachineServiceContainersR\bmessages\"\xbc\x01\n" +
	"\x18MachineServiceContainers\x12)\n" +
	"\bmetadata\x18\x01 \x01(\v2\r.api.MetadataR\bmetadata\x125\n" +
	"\n" +
	"containers\x18\x02 \x03(\v2\x15.api.ServiceContainerR\n" +
	"containers\x12>\n" +
	"\x0fhook_containers\x18\x03 \x03(\v2\x15.api.ServiceContainerR\x0ehookContainers2\xfb\n" +
	"\n" +
	"\x06Docker\x12L\n" +
	"\x0fCreateContainer\x12\x1b.api.CreateContainerRequest\x1a\x1c.api.CreateContainerResponse\x12O\n" +
	"\x10InspectContainer\x12\x1c.api.InspectContainerRequest\x1a\x1d.api.InspectContainerResponse\x12D\n" +
	"\x0eStartContainer\x12\x1a.api.StartContainerRequest\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\rStopContainer\x12\x19.api.StopContainerRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\x0eListContainers\x12\x1a.api.ListContainersRequest\x1a\x1b.api.ListContainersResponse\x12F\n" +
	"\x0fRemoveContainer\x12\x1b.api.RemoveContainerRequest\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\rExecContainer\x12\x19.api.ExecContainerRequest\x1a\x1a.api.ExecContainerResponse(\x010\x01\x122\n" +
	"\rContainerLogs\x12\x10.api.LogsRequest\x1a\r.api.LogEntry0\x01\x126\n" +
	"\tPullImage\x12\x15.api.PullImageRequest\x1a\x10.api.JSONMessage0\x01\x12C\n" +
	"\fInspectImage\x12\x18.api.InspectImageRequest\x1a\x19.api.InspectImageResponse\x12U\n" +
	"\x12InspectRemoteImage\x12\x1e.api.InspectRemoteImageRequest\x1a\x1f.api.InspectRemoteImageResponse\x12=\n" +
	"\n" +
	"ListImages\x12\x16.api.ListImagesRequest\x1a\x17.api.ListImagesResponse\x12C\n" +
	"\fCreateVolume\x12\x18.api.CreateVolumeRequest\x1a\x19.api.CreateVolumeResponse\x12@\n" +
	"\vListVolumes\x12\x17.api.ListVolumesRequest\x1a\x18.api.ListVolumesResponse\x12@\n" +
	"\fRemoveVolume\x12\x18.api.RemoveVolumeRequest\x1a\x16.google.protobuf.Empty\x12Z\n" +
	"\x16CreateServiceContainer\x12\".api.CreateServiceContainerRequest\x1a\x1c.api.CreateContainerResponse\x12N\n" +
	"\x17InspectServiceContainer\x12\x1c.api.InspectContainerRequest\x1a\x15.api.ServiceContainer\x12^\n" +
	"\x15ListServiceContainers\x12!.api.ListServiceContainersRequest\x1a\".api.ListServiceContainersResponse\x12M\n" +
	"\x16RemoveServiceContainer\x12\x1b.api.RemoveContainerRequest\x1a\x16.google.protobuf.EmptyB7Z5github.com/psviderski/uncloud/internal/machine/api/pbb\x06proto3"

var (
	file_internal_machine_api_pb_docker_proto_rawDescOnce sync.Once
	file_internal_machine_api_pb_docker_proto_rawDescData []byte
)

func file_internal_machine_api_pb_docker_proto_rawDescGZIP() []byte {
	file_internal_machine_api_pb_docker_proto_rawDescOnce.Do(func() {
		file_internal_machine_api_pb_docker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_machine_api_pb_docker_proto_rawDesc), len(file_internal_machine_api_pb_docker_proto_rawDesc)))
	})
	return file_internal_machine_api_pb_docker_proto_rawDescData
}

var file_internal_machine_api_pb_docker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_machine_api_pb_docker_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_internal_machine_api_pb_docker_proto_goTypes = []any{
	(CreateServiceContainerRequest_ContainerType)(0), // 0: api.CreateServiceContainerRequest.ContainerType
	(*CreateContainerRequest)(nil),                   // 1: api.CreateContainerRequest
	(*CreateContainerResponse)(nil),                  // 2: api.CreateContainerResponse
	(*InspectContainerRequest)(nil),                  // 3: api.InspectContainerRequest
	(*InspectContainerResponse)(nil),                 // 4: api.InspectContainerResponse
	(*StartContainerRequest)(nil),                    // 5: api.StartContainerRequest
	(*StopContainerRequest)(nil),                     // 6: api.StopContainerRequest
	(*ListContainersRequest)(nil),                    // 7: api.ListContainersRequest
	(*ListContainersResponse)(nil),                   // 8: api.ListContainersResponse
	(*MachineContainers)(nil),                        // 9: api.MachineContainers
	(*RemoveContainerRequest)(nil),                   // 10: api.RemoveContainerRequest
	(*ExecContainerRequest)(nil),                     // 11: api.ExecContainerRequest
	(*ExecConfig)(nil),                               // 12: api.ExecConfig
	(*ResizeEvent)(nil),                              // 13: api.ResizeEvent
	(*ExecContainerResponse)(nil),                    // 14: api.ExecContainerResponse
	(*PullImageRequest)(nil),                         // 15: api.PullImageRequest
	(*JSONMessage)(nil),                              // 16: api.JSONMessage
	(*InspectImageRequest)(nil),                      // 17: api.InspectImageRequest
	(*InspectImageResponse)(nil),                     // 18: api.InspectImageResponse
	(*Image)(nil),                                    // 19: api.Image
	(*InspectRemoteImageRequest)(nil),                // 20: api.InspectRemoteImageRequest
	(*InspectRemoteImageResponse)(nil),               // 21: api.InspectRemoteImageResponse
	(*RemoteImage)(nil),                              // 22: api.RemoteImage
	(*ListImagesRequest)(nil),                        // 23: api.ListImagesRequest
	(*ListImagesResponse)(nil),                       // 24: api.ListImagesResponse
	(*MachineImages)(nil),                            // 25: api.MachineImages
	(*CreateVolumeRequest)(nil),                      // 26: api.CreateVolumeRequest
	(*CreateVolumeResponse)(nil),                     // 27: api.CreateVolumeResponse
	(*ListVolumesRequest)(nil),                       // 28: api.ListVolumesRequest
	(*ListVolumesResponse)(nil),                      // 29: api.ListVolumesResponse
	(*MachineVolumes)(nil),                           // 30: api.MachineVolumes
	(*RemoveVolumeRequest)(nil),                      // 31: api.RemoveVolumeRequest
	(*CreateServiceContainerRequest)(nil),            // 32: api.CreateServiceContainerRequest
	(*ServiceContainer)(nil),                         // 33: api.ServiceContainer
	(*ListServiceContainersRequest)(nil),             // 34: api.ListServiceContainersRequest
	(*ListServiceContainersResponse)(nil),            // 35: api.ListServiceContainersResponse
	(*MachineServiceContainers)(nil),                 // 36: api.MachineServiceContainers
	(*Metadata)(nil),                                 // 37: api.Metadata
	(*LogsRequest)(nil),                              // 38: api.LogsRequest
	(*emptypb.Empty)(nil),                            // 39: google.protobuf.Empty
	(*LogEntry)(nil),                                 // 40: api.LogEntry
}
var file_internal_machine_api_pb_docker_proto_depIdxs = []int32{
	9,  // 0: api.ListContainersResponse.messages:type_name -> api.MachineContainers
	37, // 1: api.MachineContainers.metadata:type_name -> api.Metadata
	12, // 2: api.ExecContainerRequest.config:type_name -> api.ExecConfig
	13, // 3: api.ExecContainerRequest.resize:type_name -> api.ResizeEvent
	19, // 4: api.InspectImageResponse.messages:type_name -> api.Image
	37, // 5: api.Image.metadata:type_name -> api.Metadata
	22, // 6: api.InspectRemoteImageResponse.messages:type_name -> api.RemoteImage
	37, // 7: api.RemoteImage.metadata:type_name -> api.Metadata
	25, // 8: api.ListImagesResponse.messages:type_name -> api.MachineImages
	37, // 9: api.MachineImages.metadata:type_name -> api.Metadata
	30, // 10: api.ListVolumesResponse.messages:type_name -> api.MachineVolumes
	37, // 11: api.MachineVolumes.metadata:type_name -> api.Metadata
	0,  // 12: api.CreateServiceContainerRequest.container_type:type_name -> api.CreateServiceContainerRequest.ContainerType
	36, // 13: api.ListServiceContainersResponse.messages:type_name -> api.MachineServiceContainers
	37, // 14: api.MachineServiceContainers.metadata:type_name -> api.Metadata
	33, // 15: api.MachineServiceContainers.containers:type_name -> api.ServiceContainer
	33, // 16: api.MachineServiceContainers.hook_containers:type_name -> api.ServiceContainer
	1,  // 17: api.Docker.CreateContainer:input_type -> api.CreateContainerRequest
	3,  // 18: api.Docker.InspectContainer:input_type -> api.InspectContainerRequest
	5,  // 19: api.Docker.StartContainer:input_type -> api.StartContainerRequest
	6,  // 20: api.Docker.StopContainer:input_type -> api.StopContainerRequest
	7,  // 21: api.Docker.ListContainers:input_type -> api.ListContainersRequest
	10, // 22: api.Docker.RemoveContainer:input_type -> api.RemoveContainerRequest
	11, // 23: api.Docker.ExecContainer:input_type -> api.ExecContainerRequest
	38, // 24: api.Docker.ContainerLogs:input_type -> api.LogsRequest
	15, // 25: api.Docker.PullImage:input_type -> api.PullImageRequest
	17, // 26: api.Docker.InspectImage:input_type -> api.InspectImageRequest
	20, // 27: api.Docker.InspectRemoteImage:input_type -> api.InspectRemoteImageRequest
	23, // 28: api.Docker.ListImages:input_type -> api.ListImagesRequest
	26, // 29: api.Docker.CreateVolume:input_type -> api.CreateVolumeRequest
	28, // 30: api.Docker.ListVolumes:input_type -> api.ListVolumesRequest
	31, // 31: api.Docker.RemoveVolume:input_type -> api.RemoveVolumeRequest
	32, // 32: api.Docker.CreateServiceContainer:input_type -> api.CreateServiceContainerRequest
	3,  // 33: api.Docker.InspectServiceContainer:input_type -> api.InspectContainerRequest
	34, // 34: api.Docker.ListServiceContainers:input_type -> api.ListServiceContainersRequest
	10, // 35: api.Docker.RemoveServiceContainer:input_type -> api.RemoveContainerRequest
	2,  // 36: api.Docker.CreateContainer:output_type -> api.CreateContainerResponse
	4,  // 37: api.Docker.InspectContainer:output_type -> api.InspectContainerResponse
	39, // 38: api.Docker.StartContainer:output_type -> google.protobuf.Empty
	39, // 39: api.Docker.StopContainer:output_type -> google.protobuf.Empty
	8,  // 40: api.Docker.ListContainers:output_type -> api.ListContainersResponse
	39, // 41: api.Docker.RemoveContainer:output_type -> google.protobuf.Empty
	14, // 42: api.Docker.ExecContainer:output_type -> api.ExecContainerResponse
	40, // 43: api.Docker.ContainerLogs:output_type -> api.LogEntry
	16, // 44: api.Docker.PullImage:output_type -> api.JSONMessage
	18, // 45: api.Docker.InspectImage:output_type -> api.InspectImageResponse
	21, // 46: api.Docker.InspectRemoteImage:output_type -> api.InspectRemoteImageResponse
	24, // 47: api.Docker.ListImages:output_type -> api.ListImagesResponse
	27, // 48: api.Docker.CreateVolume:output_type -> api.CreateVolumeResponse
	29, // 49: api.Docker.ListVolumes:output_type -> api.ListVolumesResponse
	39, // 50: api.Docker.RemoveVolume:output_type -> google.protobuf.Empty
	2,  // 51: api.Docker.CreateServiceContainer:output_type -> api.CreateContainerResponse
	33, // 52: api.Docker.InspectServiceContainer:output_type -> api.ServiceContainer
	35, // 53: api.Docker.ListServiceContainers:output_type -> api.ListServiceContainersResponse
	39, // 54: api.Docker.RemoveServiceContainer:output_type -> google.protobuf.Empty
	36, // [36:55] is the sub-list for method output_type
	17, // [17:36] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_internal_machine_api_pb_docker_proto_init() }
func file_internal_machine_api_pb_docker_proto_init() {
	if File_internal_machine_api_pb_docker_proto != nil {
		return
	}
	file_internal_machine_api_pb_common_proto_init()
	file_internal_machine_api_pb_docker_proto_msgTypes[10].OneofWrappers = []any{
		(*ExecContainerRequest_Config)(nil),
		(*ExecContainerRequest_Stdin)(nil),
		(*ExecContainerRequest_Resize)(nil),
	}
	file_internal_machine_api_pb_docker_proto_msgTypes[13].OneofWrappers = []any{
		(*ExecContainerResponse_ExecId)(nil),
		(*ExecContainerResponse_Stdout)(nil),
		(*ExecContainerResponse_Stderr)(nil),
		(*ExecContainerResponse_ExitCode)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_machine_api_pb_docker_proto_rawDesc), len(file_internal_machine_api_pb_docker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_machine_api_pb_docker_proto_goTypes,
		DependencyIndexes: file_internal_machine_api_pb_docker_proto_depIdxs,
		EnumInfos:         file_internal_machine_api_pb_docker_proto_enumTypes,
		MessageInfos:      file_internal_machine_api_pb_docker_proto_msgTypes,
	}.Build()
	File_internal_machine_api_pb_docker_proto = out.File
	file_internal_machine_api_pb_docker_proto_goTypes = nil
	file_internal_machine_api_pb_docker_proto_depIdxs = nil
}
