// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/machine/api/pb/machine.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MachineInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Network       *NetworkConfig         `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	PublicIp      *IP                    `protobuf:"bytes,4,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineInfo) Reset() {
	*x = MachineInfo{}
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineInfo) ProtoMessage() {}

func (x *MachineInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineInfo.ProtoReflect.Descriptor instead.
func (*MachineInfo) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_machine_proto_rawDescGZIP(), []int{0}
}

func (x *MachineInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MachineInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MachineInfo) GetNetwork() *NetworkConfig {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *MachineInfo) GetPublicIp() *IP {
	if x != nil {
		return x.PublicIp
	}
	return nil
}

type NetworkConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subnet        *IPPrefix              `protobuf:"bytes,1,opt,name=subnet,proto3" json:"subnet,omitempty"`
	ManagementIp  *IP                    `protobuf:"bytes,2,opt,name=management_ip,json=managementIp,proto3" json:"management_ip,omitempty"`
	Endpoints     []*IPPort              `protobuf:"bytes,3,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkConfig) Reset() {
	*x = NetworkConfig{}
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConfig) ProtoMessage() {}

func (x *NetworkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConfig.ProtoReflect.Descriptor instead.
func (*NetworkConfig) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_machine_proto_rawDescGZIP(), []int{1}
}

func (x *NetworkConfig) GetSubnet() *IPPrefix {
	if x != nil {
		return x.Subnet
	}
	return nil
}

func (x *NetworkConfig) GetManagementIp() *IP {
	if x != nil {
		return x.ManagementIp
	}
	return nil
}

func (x *NetworkConfig) GetEndpoints() []*IPPort {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *NetworkConfig) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type CheckPrerequisitesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Overall status of the checks.
	Satisfied bool `protobuf:"varint,1,opt,name=satisfied,proto3" json:"satisfied,omitempty"`
	// Error message if not satisfied (empty if all checks pass).
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPrerequisitesResponse) Reset() {
	*x = CheckPrerequisitesResponse{}
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPrerequisitesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPrerequisitesResponse) ProtoMessage() {}

func (x *CheckPrerequisitesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPrerequisitesResponse.ProtoReflect.Descriptor instead.
func (*CheckPrerequisitesResponse) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_machine_proto_rawDescGZIP(), []int{2}
}

func (x *CheckPrerequisitesResponse) GetSatisfied() bool {
	if x != nil {
		return x.Satisfied
	}
	return false
}

func (x *CheckPrerequisitesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type InitClusterRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	MachineName string                 `protobuf:"bytes,1,opt,name=machineName,proto3" json:"machineName,omitempty"`
	Network     *IPPrefix              `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	// Types that are valid to be assigned to PublicIpConfig:
	//
	//	*InitClusterRequest_PublicIp
	//	*InitClusterRequest_PublicIpAuto
	PublicIpConfig isInitClusterRequest_PublicIpConfig `protobuf_oneof:"public_ip_config"`
	// Optional WireGuard endpoints other machines will use to connect to this machine instead of auto-discovered ones.
	WireguardEndpoints []*IPPort `protobuf:"bytes,5,rep,name=wireguard_endpoints,json=wireguardEndpoints,proto3" json:"wireguard_endpoints,omitempty"`
	// WireGuard listen port for this machine. Uses the default port (51820) if 0 or not set.
	WireguardPort int32 `protobuf:"varint,6,opt,name=wireguard_port,json=wireguardPort,proto3" json:"wireguard_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitClusterRequest) Reset() {
	*x = InitClusterRequest{}
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitClusterRequest) ProtoMessage() {}

func (x *InitClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitClusterRequest.ProtoReflect.Descriptor instead.
func (*InitClusterRequest) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_machine_proto_rawDescGZIP(), []int{3}
}

func (x *InitClusterRequest) GetMachineName() string {
	if x != nil {
		return x.MachineName
	}
	return ""
}

func (x *InitClusterRequest) GetNetwork() *IPPrefix {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *InitClusterRequest) GetPublicIpConfig() isInitClusterRequest_PublicIpConfig {
	if x != nil {
		return x.PublicIpConfig
	}
	return nil
}

func (x *InitClusterRequest) GetPublicIp() *IP {
	if x != nil {
		if x, ok := x.PublicIpConfig.(*InitClusterRequest_PublicIp); ok {
			return x.PublicIp
		}
	}
	return nil
}

func (x *InitClusterRequest) GetPublicIpAuto() bool {
	if x != nil {
		if x, ok := x.PublicIpConfig.(*InitClusterRequest_PublicIpAuto); ok {
			return x.PublicIpAuto
		}
	}
	return false
}

func (x *InitClusterRequest) GetWireguardEndpoints() []*IPPort {
	if x != nil {
		return x.WireguardEndpoints
	}
	return nil
}

func (x *InitClusterRequest) GetWireguardPort() int32 {
	if x != nil {
		return x.WireguardPort
	}
	return 0
}

type isInitClusterRequest_PublicIpConfig interface {
	isInitClusterRequest_PublicIpConfig()
}

type InitClusterRequest_PublicIp struct {
	PublicIp *IP `protobuf:"bytes,3,opt,name=public_ip,json=publicIp,proto3,oneof"`
}

type InitClusterRequest_PublicIpAuto struct {
	PublicIpAuto bool `protobuf:"varint,4,opt,name=public_ip_auto,json=publicIpAuto,proto3,oneof"`
}

func (*InitClusterRequest_PublicIp) isInitClusterRequest_PublicIpConfig() {}

func (*InitClusterRequest_PublicIpAuto) isInitClusterRequest_PublicIpConfig() {}

type InitClusterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Machine       *MachineInfo           `protobuf:"bytes,1,opt,name=machine,proto3" json:"machine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitClusterResponse) Reset() {
	*x = InitClusterResponse{}
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitClusterResponse) ProtoMessage() {}

func (x *InitClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitClusterResponse.ProtoReflect.Descriptor instead.
func (*InitClusterResponse) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_machine_proto_rawDescGZIP(), []int{4}
}

func (x *InitClusterResponse) GetMachine() *MachineInfo {
	if x != nil {
		return x.Machine
	}
	return nil
}

type JoinClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Machine       *MachineInfo           `protobuf:"bytes,1,opt,name=machine,proto3" json:"machine,omitempty"`
	OtherMachines []*MachineInfo         `protobuf:"bytes,3,rep,name=other_machines,json=otherMachines,proto3" json:"other_machines,omitempty"`
	// Minimum store database version the new machine should sync to before starting cluster operations.
	MinStoreDbVersion int64 `protobuf:"varint,4,opt,name=min_store_db_version,json=minStoreDbVersion,proto3" json:"min_store_db_version,omitempty"`
	// WireGuard listen port for this machine. Uses the default port (51820) if 0 or not set.
	WireguardPort int32 `protobuf:"varint,5,opt,name=wireguard_port,json=wireguardPort,proto3" json:"wireguard_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinClusterRequest) Reset() {
	*x = JoinClusterRequest{}
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinClusterRequest) ProtoMessage() {}

func (x *JoinClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinClusterRequest.ProtoReflect.Descriptor instead.
func (*JoinClusterRequest) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_machine_proto_rawDescGZIP(), []int{5}
}

func (x *JoinClusterRequest) GetMachine() *MachineInfo {
	if x != nil {
		return x.Machine
	}
	return nil
}

func (x *JoinClusterRequest) GetOtherMachines() []*MachineInfo {
	if x != nil {
		return x.OtherMachines
	}
	return nil
}

func (x *JoinClusterRequest) GetMinStoreDbVersion() int64 {
	if x != nil {
		return x.MinStoreDbVersion
	}
	return 0
}

func (x *JoinClusterRequest) GetWireguardPort() int32 {
	if x != nil {
		return x.WireguardPort
	}
	return 0
}

type InspectMachineResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Must contain only one repeated messages field to allow broadcasting InspectMachine requests to multiple machines.
	Machines      []*MachineDetails `protobuf:"bytes,1,rep,name=machines,proto3" json:"machines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectMachineResponse) Reset() {
	*x = InspectMachineResponse{}
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectMachineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectMachineResponse) ProtoMessage() {}

func (x *InspectMachineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectMachineResponse.ProtoReflect.Descriptor instead.
func (*InspectMachineResponse) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_machine_proto_rawDescGZIP(), []int{6}
}

func (x *InspectMachineResponse) GetMachines() []*MachineDetails {
	if x != nil {
		return x.Machines
	}
	return nil
}

type MachineDetails struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Metadata *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Machine  *MachineInfo           `protobuf:"bytes,2,opt,name=machine,proto3" json:"machine,omitempty"`
	// Current Corrosion cr-sqlite database version (Lamport timestamp) of the cluster store.
	StoreDbVersion int64 `protobuf:"varint,3,opt,name=store_db_version,json=storeDbVersion,proto3" json:"store_db_version,omitempty"`
	// Round-trip times to other machines in the cluster, keyed by peer machine ID.
	Rtts          map[string]*RTTStats `protobuf:"bytes,4,rep,name=rtts,proto3" json:"rtts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineDetails) Reset() {
	*x = MachineDetails{}
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineDetails) ProtoMessage() {}

func (x *MachineDetails) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineDetails.ProtoReflect.Descriptor instead.
func (*MachineDetails) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_machine_proto_rawDescGZIP(), []int{7}
}

func (x *MachineDetails) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MachineDetails) GetMachine() *MachineInfo {
	if x != nil {
		return x.Machine
	}
	return nil
}

func (x *MachineDetails) GetStoreDbVersion() int64 {
	if x != nil {
		return x.StoreDbVersion
	}
	return 0
}

func (x *MachineDetails) GetRtts() map[string]*RTTStats {
	if x != nil {
		return x.Rtts
	}
	return nil
}

type TokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_machine_proto_rawDescGZIP(), []int{8}
}

func (x *TokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_machine_proto_rawDescGZIP(), []int{9}
}

type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Containers    []*Service_Container   `protobuf:"bytes,4,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_machine_proto_rawDescGZIP(), []int{10}
}

func (x *Service) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *Service) GetContainers() []*Service_Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

type InspectServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectServiceRequest) Reset() {
	*x = InspectServiceRequest{}
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectServiceRequest) ProtoMessage() {}

func (x *InspectServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectServiceRequest.ProtoReflect.Descriptor instead.
func (*InspectServiceRequest) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_machine_proto_rawDescGZIP(), []int{11}
}

func (x *InspectServiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type InspectServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *Service               `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectServiceResponse) Reset() {
	*x = InspectServiceResponse{}
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectServiceResponse) ProtoMessage() {}

func (x *InspectServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectServiceResponse.ProtoReflect.Descriptor instead.
func (*InspectServiceResponse) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_machine_proto_rawDescGZIP(), []int{12}
}

func (x *InspectServiceResponse) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

type InspectWireGuardNetworkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterfaceName string                 `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	ListenPort    int32                  `protobuf:"varint,3,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	Peers         []*WireGuardPeer       `protobuf:"bytes,4,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectWireGuardNetworkResponse) Reset() {
	*x = InspectWireGuardNetworkResponse{}
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectWireGuardNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectWireGuardNetworkResponse) ProtoMessage() {}

func (x *InspectWireGuardNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectWireGuardNetworkResponse.ProtoReflect.Descriptor instead.
func (*InspectWireGuardNetworkResponse) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_machine_proto_rawDescGZIP(), []int{13}
}

func (x *InspectWireGuardNetworkResponse) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *InspectWireGuardNetworkResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *InspectWireGuardNetworkResponse) GetListenPort() int32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *InspectWireGuardNetworkResponse) GetPeers() []*WireGuardPeer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type WireGuardPeer struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PublicKey         []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Endpoint          string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	LastHandshakeTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_handshake_time,json=lastHandshakeTime,proto3" json:"last_handshake_time,omitempty"`
	ReceiveBytes      int64                  `protobuf:"varint,4,opt,name=receive_bytes,json=receiveBytes,proto3" json:"receive_bytes,omitempty"`
	TransmitBytes     int64                  `protobuf:"varint,5,opt,name=transmit_bytes,json=transmitBytes,proto3" json:"transmit_bytes,omitempty"`
	AllowedIps        []string               `protobuf:"bytes,6,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WireGuardPeer) Reset() {
	*x = WireGuardPeer{}
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireGuardPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireGuardPeer) ProtoMessage() {}

func (x *WireGuardPeer) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireGuardPeer.ProtoReflect.Descriptor instead.
func (*WireGuardPeer) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_machine_proto_rawDescGZIP(), []int{14}
}

func (x *WireGuardPeer) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *WireGuardPeer) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *WireGuardPeer) GetLastHandshakeTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHandshakeTime
	}
	return nil
}

func (x *WireGuardPeer) GetReceiveBytes() int64 {
	if x != nil {
		return x.ReceiveBytes
	}
	return 0
}

func (x *WireGuardPeer) GetTransmitBytes() int64 {
	if x != nil {
		return x.TransmitBytes
	}
	return 0
}

func (x *WireGuardPeer) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

type RTTStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Median        *durationpb.Duration   `protobuf:"bytes,1,opt,name=median,proto3" json:"median,omitempty"`
	StdDev        *durationpb.Duration   `protobuf:"bytes,2,opt,name=std_dev,json=stdDev,proto3" json:"std_dev,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTTStats) Reset() {
	*x = RTTStats{}
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTTStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTTStats) ProtoMessage() {}

func (x *RTTStats) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTTStats.ProtoReflect.Descriptor instead.
func (*RTTStats) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_machine_proto_rawDescGZIP(), []int{15}
}

func (x *RTTStats) GetMedian() *durationpb.Duration {
	if x != nil {
		return x.Median
	}
	return nil
}

func (x *RTTStats) GetStdDev() *durationpb.Duration {
	if x != nil {
		return x.StdDev
	}
	return nil
}

type Service_Container struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MachineId string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	// JSON encoded Docker types.Container.
	Container     []byte `protobuf:"bytes,2,opt,name=container,proto3" json:"container,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service_Container) Reset() {
	*x = Service_Container{}
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service_Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service_Container) ProtoMessage() {}

func (x *Service_Container) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service_Container.ProtoReflect.Descriptor instead.
func (*Service_Container) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_machine_proto_rawDescGZIP(), []int{10, 0}
}

func (x *Service_Container) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *Service_Container) GetContainer() []byte {
	if x != nil {
		return x.Container
	}
	return nil
}

var File_internal_machine_api_pb_machine_proto protoreflect.FileDescriptor

const file_internal_machine_api_pb_machine_proto_rawDesc = "" +
	"\n" +
	"%internal/machine/api/pb/machine.proto\x12\x03api\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a$internal/machine/api/pb/common.proto\"\x85\x01\n" +
	"\vMachineInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12,\n" +
	"\anetwork\x18\x03 \x01(\v2\x12.api.NetworkConfigR\anetwork\x12$\n" +
	"\tpublic_ip\x18\x04 \x01(\v2\a.api.IPR\bpublicIp\"\xae\x01\n" +
	"\rNetworkConfig\x12%\n" +
	"\x06subnet\x18\x01 \x01(\v2\r.api.IPPrefixR\x06subnet\x12,\n" +
	"\rmanagement_ip\x18\x02 \x01(\v2\a.api.IPR\fmanagementIp\x12)\n" +
	"\tendpoints\x18\x03 \x03(\v2\v.api.IPPortR\tendpoints\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\fR\tpublicKey\"P\n" +
	"\x1aCheckPrerequisitesResponse\x12\x1c\n" +
	"\tsatisfied\x18\x01 \x01(\bR\tsatisfied\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xa8\x02\n" +
	"\x12InitClusterRequest\x12 \n" +
	"\vmachineName\x18\x01 \x01(\tR\vmachineName\x12'\n" +
	"\anetwork\x18\x02 \x01(\v2\r.api.IPPrefixR\anetwork\x12&\n" +
	"\tpublic_ip\x18\x03 \x01(\v2\a.api.IPH\x00R\bpublicIp\x12&\n" +
	"\x0epublic_ip_auto\x18\x04 \x01(\bH\x00R\fpublicIpAuto\x12<\n" +
	"\x13wireguard_endpoints\x18\x05 \x03(\v2\v.api.IPPortR\x12wireguardEndpoints\x12%\n" +
	"\x0ewireguard_port\x18\x06 \x01(\x05R\rwireguardPortB\x12\n" +
	"\x10public_ip_config\"A\n" +
	"\x13InitClusterResponse\x12*\n" +
	"\amachine\x18\x01 \x01(\v2\x10.api.MachineInfoR\amachine\"\xd1\x01\n" +
	"\x12JoinClusterRequest\x12*\n" +
	"\amachine\x18\x01 \x01(\v2\x10.api.MachineInfoR\amachine\x127\n" +
	"\x0eother_machines\x18\x03 \x03(\v2\x10.api.MachineInfoR\rotherMachines\x12/\n" +
	"\x14min_store_db_version\x18\x04 \x01(\x03R\x11minStoreDbVersion\x12%\n" +
	"\x0ewireguard_port\x18\x05 \x01(\x05R\rwireguardPort\"I\n" +
	"\x16InspectMachineResponse\x12/\n" +
	"\bmachines\x18\x01 \x03(\v2\x13.api.MachineDetailsR\bmachines\"\x8c\x02\n" +
	"\x0eMachineDetails\x12)\n" +
	"\bmetadata\x18\x01 \x01(\v2\r.api.MetadataR\bmetadata\x12*\n" +
	"\amachine\x18\x02 \x01(\v2\x10.api.MachineInfoR\amachine\x12(\n" +
	"\x10store_db_version\x18\x03 \x01(\x03R\x0estoreDbVersion\x121\n" +
	"\x04rtts\x18\x04 \x03(\v2\x1d.api.MachineDetails.RttsEntryR\x04rtts\x1aF\n" +
	"\tRttsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.api.RTTStatsR\x05value:\x028\x01\"%\n" +
	"\rTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x0e\n" +
	"\fResetRequest\"\xc3\x01\n" +
	"\aService\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x126\n" +
	"\n" +
	"containers\x18\x04 \x03(\v2\x16.api.Service.ContainerR\n" +
	"containers\x1aH\n" +
	"\tContainer\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12\x1c\n" +
	"\tcontainer\x18\x02 \x01(\fR\tcontainer\"'\n" +
	"\x15InspectServiceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x16InspectServiceResponse\x12&\n" +
	"\aservice\x18\x01 \x01(\v2\f.api.ServiceR\aservice\"\xb2\x01\n" +
	"\x1fInspectWireGuardNetworkResponse\x12%\n" +
	"\x0einterface_name\x18\x01 \x01(\tR\rinterfaceName\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12\x1f\n" +
	"\vlisten_port\x18\x03 \x01(\x05R\n" +
	"listenPort\x12(\n" +
	"\x05peers\x18\x04 \x03(\v2\x12.api.WireGuardPeerR\x05peers\"\x83\x02\n" +
	"\rWireGuardPeer\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12J\n" +
	"\x13last_handshake_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x11lastHandshakeTime\x12#\n" +
	"\rreceive_bytes\x18\x04 \x01(\x03R\freceiveBytes\x12%\n" +
	"\x0etransmit_bytes\x18\x05 \x01(\x03R\rtransmitBytes\x12\x1f\n" +
	"\vallowed_ips\x18\x06 \x03(\tR\n" +
	"allowedIps\"q\n" +
	"\bRTTStats\x121\n" +
	"\x06median\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x06median\x122\n" +
	"\astd_dev\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x06stdDev2\x95\x05\n" +
	"\aMachine\x12M\n" +
	"\x12CheckPrerequisites\x12\x16.google.protobuf.Empty\x1a\x1f.api.CheckPrerequisitesResponse\x12@\n" +
	"\vInitCluster\x12\x17.api.InitClusterRequest\x1a\x18.api.InitClusterResponse\x12>\n" +
	"\vJoinCluster\x12\x17.api.JoinClusterRequest\x1a\x16.google.protobuf.Empty\x123\n" +
	"\x05Token\x12\x16.google.protobuf.Empty\x1a\x12.api.TokenResponse\x123\n" +
	"\aInspect\x12\x16.google.protobuf.Empty\x1a\x10.api.MachineInfo\x12E\n" +
	"\x0eInspectMachine\x12\x16.google.protobuf.Empty\x1a\x1b.api.InspectMachineResponse\x12W\n" +
	"\x17InspectWireGuardNetwork\x12\x16.google.protobuf.Empty\x1a$.api.InspectWireGuardNetworkResponse\x122\n" +
	"\x05Reset\x12\x11.api.ResetRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\x0eInspectService\x12\x1a.api.InspectServiceRequest\x1a\x1b.api.InspectServiceResponse\x120\n" +
	"\vMachineLogs\x12\x10.api.LogsRequest\x1a\r.api.LogEntry0\x01B7Z5github.com/psviderski/uncloud/internal/machine/api/pbb\x06proto3"

var (
	file_internal_machine_api_pb_machine_proto_rawDescOnce sync.Once
	file_internal_machine_api_pb_machine_proto_rawDescData []byte
)

func file_internal_machine_api_pb_machine_proto_rawDescGZIP() []byte {
	file_internal_machine_api_pb_machine_proto_rawDescOnce.Do(func() {
		file_internal_machine_api_pb_machine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_machine_api_pb_machine_proto_rawDesc), len(file_internal_machine_api_pb_machine_proto_rawDesc)))
	})
	return file_internal_machine_api_pb_machine_proto_rawDescData
}

var file_internal_machine_api_pb_machine_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_internal_machine_api_pb_machine_proto_goTypes = []any{
	(*MachineInfo)(nil),                     // 0: api.MachineInfo
	(*NetworkConfig)(nil),                   // 1: api.NetworkConfig
	(*CheckPrerequisitesResponse)(nil),      // 2: api.CheckPrerequisitesResponse
	(*InitClusterRequest)(nil),              // 3: api.InitClusterRequest
	(*InitClusterResponse)(nil),             // 4: api.InitClusterResponse
	(*JoinClusterRequest)(nil),              // 5: api.JoinClusterRequest
	(*InspectMachineResponse)(nil),          // 6: api.InspectMachineResponse
	(*MachineDetails)(nil),                  // 7: api.MachineDetails
	(*TokenResponse)(nil),                   // 8: api.TokenResponse
	(*ResetRequest)(nil),                    // 9: api.ResetRequest
	(*Service)(nil),                         // 10: api.Service
	(*InspectServiceRequest)(nil),           // 11: api.InspectServiceRequest
	(*InspectServiceResponse)(nil),          // 12: api.InspectServiceResponse
	(*InspectWireGuardNetworkResponse)(nil), // 13: api.InspectWireGuardNetworkResponse
	(*WireGuardPeer)(nil),                   // 14: api.WireGuardPeer
	(*RTTStats)(nil),                        // 15: api.RTTStats
	nil,                                     // 16: api.MachineDetails.RttsEntry
	(*Service_Container)(nil),               // 17: api.Service.Container
	(*IP)(nil),                              // 18: api.IP
	(*IPPrefix)(nil),                        // 19: api.IPPrefix
	(*IPPort)(nil),                          // 20: api.IPPort
	(*Metadata)(nil),                        // 21: api.Metadata
	(*timestamppb.Timestamp)(nil),           // 22: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),             // 23: google.protobuf.Duration
	(*emptypb.Empty)(nil),                   // 24: google.protobuf.Empty
	(*LogsRequest)(nil),                     // 25: api.LogsRequest
	(*LogEntry)(nil),                        // 26: api.LogEntry
}
var file_internal_machine_api_pb_machine_proto_depIdxs = []int32{
	1,  // 0: api.MachineInfo.network:type_name -> api.NetworkConfig
	18, // 1: api.MachineInfo.public_ip:type_name -> api.IP
	19, // 2: api.NetworkConfig.subnet:type_name -> api.IPPrefix
	18, // 3: api.NetworkConfig.management_ip:type_name -> api.IP
	20, // 4: api.NetworkConfig.endpoints:type_name -> api.IPPort
	19, // 5: api.InitClusterRequest.network:type_name -> api.IPPrefix
	18, // 6: api.InitClusterRequest.public_ip:type_name -> api.IP
	20, // 7: api.InitClusterRequest.wireguard_endpoints:type_name -> api.IPPort
	0,  // 8: api.InitClusterResponse.machine:type_name -> api.MachineInfo
	0,  // 9: api.JoinClusterRequest.machine:type_name -> api.MachineInfo
	0,  // 10: api.JoinClusterRequest.other_machines:type_name -> api.MachineInfo
	7,  // 11: api.InspectMachineResponse.machines:type_name -> api.MachineDetails
	21, // 12: api.MachineDetails.metadata:type_name -> api.Metadata
	0,  // 13: api.MachineDetails.machine:type_name -> api.MachineInfo
	16, // 14: api.MachineDetails.rtts:type_name -> api.MachineDetails.RttsEntry
	17, // 15: api.Service.containers:type_name -> api.Service.Container
	10, // 16: api.InspectServiceResponse.service:type_name -> api.Service
	14, // 17: api.InspectWireGuardNetworkResponse.peers:type_name -> api.WireGuardPeer
	22, // 18: api.WireGuardPeer.last_handshake_time:type_name -> google.protobuf.Timestamp
	23, // 19: api.RTTStats.median:type_name -> google.protobuf.Duration
	23, // 20: api.RTTStats.std_dev:type_name -> google.protobuf.Duration
	15, // 21: api.MachineDetails.RttsEntry.value:type_name -> api.RTTStats
	24, // 22: api.Machine.CheckPrerequisites:input_type -> google.protobuf.Empty
	3,  // 23: api.Machine.InitCluster:input_type -> api.InitClusterRequest
	5,  // 24: api.Machine.JoinCluster:input_type -> api.JoinClusterRequest
	24, // 25: api.Machine.Token:input_type -> google.protobuf.Empty
	24, // 26: api.Machine.Inspect:input_type -> google.protobuf.Empty
	24, // 27: api.Machine.InspectMachine:input_type -> google.protobuf.Empty
	24, // 28: api.Machine.InspectWireGuardNetwork:input_type -> google.protobuf.Empty
	9,  // 29: api.Machine.Reset:input_type -> api.ResetRequest
	11, // 30: api.Machine.InspectService:input_type -> api.InspectServiceRequest
	25, // 31: api.Machine.MachineLogs:input_type -> api.LogsRequest
	2,  // 32: api.Machine.CheckPrerequisites:output_type -> api.CheckPrerequisitesResponse
	4,  // 33: api.Machine.InitCluster:output_type -> api.InitClusterResponse
	24, // 34: api.Machine.JoinCluster:output_type -> google.protobuf.Empty
	8,  // 35: api.Machine.Token:output_type -> api.TokenResponse
	0,  // 36: api.Machine.Inspect:output_type -> api.MachineInfo
	6,  // 37: api.Machine.InspectMachine:output_type -> api.InspectMachineResponse
	13, // 38: api.Machine.InspectWireGuardNetwork:output_type -> api.InspectWireGuardNetworkResponse
	24, // 39: api.Machine.Reset:output_type -> google.protobuf.Empty
	12, // 40: api.Machine.InspectService:output_type -> api.InspectServiceResponse
	26, // 41: api.Machine.MachineLogs:output_type -> api.LogEntry
	32, // [32:42] is the sub-list for method output_type
	22, // [22:32] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_internal_machine_api_pb_machine_proto_init() }
func file_internal_machine_api_pb_machine_proto_init() {
	if File_internal_machine_api_pb_machine_proto != nil {
		return
	}
	file_internal_machine_api_pb_common_proto_init()
	file_internal_machine_api_pb_machine_proto_msgTypes[3].OneofWrappers = []any{
		(*InitClusterRequest_PublicIp)(nil),
		(*InitClusterRequest_PublicIpAuto)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_machine_api_pb_machine_proto_rawDesc), len(file_internal_machine_api_pb_machine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_machine_api_pb_machine_proto_goTypes,
		DependencyIndexes: file_internal_machine_api_pb_machine_proto_depIdxs,
		MessageInfos:      file_internal_machine_api_pb_machine_proto_msgTypes,
	}.Build()
	File_internal_machine_api_pb_machine_proto = out.File
	file_internal_machine_api_pb_machine_proto_goTypes = nil
	file_internal_machine_api_pb_machine_proto_depIdxs = nil
}
