// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: internal/machine/api/pb/machine.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogsRequestService int32

const (
	LogsRequest_UNCLOUD   LogsRequestService = 0
	LogsRequest_DOCKER    LogsRequestService = 1
	LogsRequest_CORROSION LogsRequestService = 2
)

// Enum value maps for LogsRequestService.
var (
	LogsRequestService_name = map[int32]string{
		0: "UNCLOUD",
		1: "DOCKER",
		2: "CORROSION",
	}
	LogsRequestService_value = map[string]int32{
		"UNCLOUD":   0,
		"DOCKER":    1,
		"CORROSION": 2,
	}
)

func (x LogsRequestService) Enum() *LogsRequestService {
	p := new(LogsRequestService)
	*p = x
	return p
}

func (x LogsRequestService) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogsRequestService) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_machine_api_pb_machine_proto_enumTypes[0].Descriptor()
}

func (LogsRequestService) Type() protoreflect.EnumType {
	return &file_internal_machine_api_pb_machine_proto_enumTypes[0]
}

func (x LogsRequestService) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogsRequestService.Descriptor instead.
func (LogsRequestService) EnumDescriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_machine_proto_rawDescGZIP(), []int{15, 0}
}

type LogEntry_StreamType int32

const (
	LogEntry_UNKNOWN   LogEntry_StreamType = 0
	LogEntry_STDOUT    LogEntry_StreamType = 1
	LogEntry_STDERR    LogEntry_StreamType = 2
	LogEntry_HEARTBEAT LogEntry_StreamType = 3
)

// Enum value maps for LogEntry_StreamType.
var (
	LogEntry_StreamType_name = map[int32]string{
		0: "UNKNOWN",
		1: "STDOUT",
		2: "STDERR",
		3: "HEARTBEAT",
	}
	LogEntry_StreamType_value = map[string]int32{
		"UNKNOWN":   0,
		"STDOUT":    1,
		"STDERR":    2,
		"HEARTBEAT": 3,
	}
)

func (x LogEntry_StreamType) Enum() *LogEntry_StreamType {
	p := new(LogEntry_StreamType)
	*p = x
	return p
}

func (x LogEntry_StreamType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogEntry_StreamType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_machine_api_pb_machine_proto_enumTypes[1].Descriptor()
}

func (LogEntry_StreamType) Type() protoreflect.EnumType {
	return &file_internal_machine_api_pb_machine_proto_enumTypes[1]
}

func (x LogEntry_StreamType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogEntry_StreamType.Descriptor instead.
func (LogEntry_StreamType) EnumDescriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_machine_proto_rawDescGZIP(), []int{16, 0}
}

type MachineInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Network       *NetworkConfig         `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	PublicIp      *IP                    `protobuf:"bytes,4,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineInfo) Reset() {
	*x = MachineInfo{}
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineInfo) ProtoMessage() {}

func (x *MachineInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineInfo.ProtoReflect.Descriptor instead.
func (*MachineInfo) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_machine_proto_rawDescGZIP(), []int{0}
}

func (x *MachineInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MachineInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MachineInfo) GetNetwork() *NetworkConfig {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *MachineInfo) GetPublicIp() *IP {
	if x != nil {
		return x.PublicIp
	}
	return nil
}

type NetworkConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subnet        *IPPrefix              `protobuf:"bytes,1,opt,name=subnet,proto3" json:"subnet,omitempty"`
	ManagementIp  *IP                    `protobuf:"bytes,2,opt,name=management_ip,json=managementIp,proto3" json:"management_ip,omitempty"`
	Endpoints     []*IPPort              `protobuf:"bytes,3,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkConfig) Reset() {
	*x = NetworkConfig{}
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConfig) ProtoMessage() {}

func (x *NetworkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConfig.ProtoReflect.Descriptor instead.
func (*NetworkConfig) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_machine_proto_rawDescGZIP(), []int{1}
}

func (x *NetworkConfig) GetSubnet() *IPPrefix {
	if x != nil {
		return x.Subnet
	}
	return nil
}

func (x *NetworkConfig) GetManagementIp() *IP {
	if x != nil {
		return x.ManagementIp
	}
	return nil
}

func (x *NetworkConfig) GetEndpoints() []*IPPort {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *NetworkConfig) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type CheckPrerequisitesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Overall status of the checks.
	Satisfied bool `protobuf:"varint,1,opt,name=satisfied,proto3" json:"satisfied,omitempty"`
	// Error message if not satisfied (empty if all checks pass).
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPrerequisitesResponse) Reset() {
	*x = CheckPrerequisitesResponse{}
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPrerequisitesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPrerequisitesResponse) ProtoMessage() {}

func (x *CheckPrerequisitesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPrerequisitesResponse.ProtoReflect.Descriptor instead.
func (*CheckPrerequisitesResponse) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_machine_proto_rawDescGZIP(), []int{2}
}

func (x *CheckPrerequisitesResponse) GetSatisfied() bool {
	if x != nil {
		return x.Satisfied
	}
	return false
}

func (x *CheckPrerequisitesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type InitClusterRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	MachineName string                 `protobuf:"bytes,1,opt,name=machineName,proto3" json:"machineName,omitempty"`
	Network     *IPPrefix              `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	// Types that are valid to be assigned to PublicIpConfig:
	//
	//	*InitClusterRequest_PublicIp
	//	*InitClusterRequest_PublicIpAuto
	PublicIpConfig isInitClusterRequest_PublicIpConfig `protobuf_oneof:"public_ip_config"`
	// Optional WireGuard endpoints other machines will use to connect to this machine instead of auto-discovered ones.
	WireguardEndpoints []*IPPort `protobuf:"bytes,5,rep,name=wireguard_endpoints,json=wireguardEndpoints,proto3" json:"wireguard_endpoints,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InitClusterRequest) Reset() {
	*x = InitClusterRequest{}
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitClusterRequest) ProtoMessage() {}

func (x *InitClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitClusterRequest.ProtoReflect.Descriptor instead.
func (*InitClusterRequest) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_machine_proto_rawDescGZIP(), []int{3}
}

func (x *InitClusterRequest) GetMachineName() string {
	if x != nil {
		return x.MachineName
	}
	return ""
}

func (x *InitClusterRequest) GetNetwork() *IPPrefix {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *InitClusterRequest) GetPublicIpConfig() isInitClusterRequest_PublicIpConfig {
	if x != nil {
		return x.PublicIpConfig
	}
	return nil
}

func (x *InitClusterRequest) GetPublicIp() *IP {
	if x != nil {
		if x, ok := x.PublicIpConfig.(*InitClusterRequest_PublicIp); ok {
			return x.PublicIp
		}
	}
	return nil
}

func (x *InitClusterRequest) GetPublicIpAuto() bool {
	if x != nil {
		if x, ok := x.PublicIpConfig.(*InitClusterRequest_PublicIpAuto); ok {
			return x.PublicIpAuto
		}
	}
	return false
}

func (x *InitClusterRequest) GetWireguardEndpoints() []*IPPort {
	if x != nil {
		return x.WireguardEndpoints
	}
	return nil
}

type isInitClusterRequest_PublicIpConfig interface {
	isInitClusterRequest_PublicIpConfig()
}

type InitClusterRequest_PublicIp struct {
	PublicIp *IP `protobuf:"bytes,3,opt,name=public_ip,json=publicIp,proto3,oneof"`
}

type InitClusterRequest_PublicIpAuto struct {
	PublicIpAuto bool `protobuf:"varint,4,opt,name=public_ip_auto,json=publicIpAuto,proto3,oneof"`
}

func (*InitClusterRequest_PublicIp) isInitClusterRequest_PublicIpConfig() {}

func (*InitClusterRequest_PublicIpAuto) isInitClusterRequest_PublicIpConfig() {}

type InitClusterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Machine       *MachineInfo           `protobuf:"bytes,1,opt,name=machine,proto3" json:"machine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitClusterResponse) Reset() {
	*x = InitClusterResponse{}
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitClusterResponse) ProtoMessage() {}

func (x *InitClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitClusterResponse.ProtoReflect.Descriptor instead.
func (*InitClusterResponse) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_machine_proto_rawDescGZIP(), []int{4}
}

func (x *InitClusterResponse) GetMachine() *MachineInfo {
	if x != nil {
		return x.Machine
	}
	return nil
}

type JoinClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Machine       *MachineInfo           `protobuf:"bytes,1,opt,name=machine,proto3" json:"machine,omitempty"`
	OtherMachines []*MachineInfo         `protobuf:"bytes,3,rep,name=other_machines,json=otherMachines,proto3" json:"other_machines,omitempty"`
	// Minimum store database version the new machine should sync to before starting cluster operations.
	MinStoreDbVersion int64 `protobuf:"varint,4,opt,name=min_store_db_version,json=minStoreDbVersion,proto3" json:"min_store_db_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *JoinClusterRequest) Reset() {
	*x = JoinClusterRequest{}
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinClusterRequest) ProtoMessage() {}

func (x *JoinClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinClusterRequest.ProtoReflect.Descriptor instead.
func (*JoinClusterRequest) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_machine_proto_rawDescGZIP(), []int{5}
}

func (x *JoinClusterRequest) GetMachine() *MachineInfo {
	if x != nil {
		return x.Machine
	}
	return nil
}

func (x *JoinClusterRequest) GetOtherMachines() []*MachineInfo {
	if x != nil {
		return x.OtherMachines
	}
	return nil
}

func (x *JoinClusterRequest) GetMinStoreDbVersion() int64 {
	if x != nil {
		return x.MinStoreDbVersion
	}
	return 0
}

type InspectMachineResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Must contain only one repeated messages field to allow broadcasting InspectMachine requests to multiple machines.
	Machines      []*MachineDetails `protobuf:"bytes,1,rep,name=machines,proto3" json:"machines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectMachineResponse) Reset() {
	*x = InspectMachineResponse{}
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectMachineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectMachineResponse) ProtoMessage() {}

func (x *InspectMachineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectMachineResponse.ProtoReflect.Descriptor instead.
func (*InspectMachineResponse) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_machine_proto_rawDescGZIP(), []int{6}
}

func (x *InspectMachineResponse) GetMachines() []*MachineDetails {
	if x != nil {
		return x.Machines
	}
	return nil
}

type MachineDetails struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Metadata *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Machine  *MachineInfo           `protobuf:"bytes,2,opt,name=machine,proto3" json:"machine,omitempty"`
	// Current Corrosion cr-sqlite database version (Lamport timestamp) of the cluster store.
	StoreDbVersion int64 `protobuf:"varint,3,opt,name=store_db_version,json=storeDbVersion,proto3" json:"store_db_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MachineDetails) Reset() {
	*x = MachineDetails{}
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineDetails) ProtoMessage() {}

func (x *MachineDetails) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineDetails.ProtoReflect.Descriptor instead.
func (*MachineDetails) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_machine_proto_rawDescGZIP(), []int{7}
}

func (x *MachineDetails) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MachineDetails) GetMachine() *MachineInfo {
	if x != nil {
		return x.Machine
	}
	return nil
}

func (x *MachineDetails) GetStoreDbVersion() int64 {
	if x != nil {
		return x.StoreDbVersion
	}
	return 0
}

type TokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_machine_proto_rawDescGZIP(), []int{8}
}

func (x *TokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_machine_proto_rawDescGZIP(), []int{9}
}

type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Containers    []*Service_Container   `protobuf:"bytes,4,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_machine_proto_rawDescGZIP(), []int{10}
}

func (x *Service) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *Service) GetContainers() []*Service_Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

type InspectServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectServiceRequest) Reset() {
	*x = InspectServiceRequest{}
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectServiceRequest) ProtoMessage() {}

func (x *InspectServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectServiceRequest.ProtoReflect.Descriptor instead.
func (*InspectServiceRequest) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_machine_proto_rawDescGZIP(), []int{11}
}

func (x *InspectServiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type InspectServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *Service               `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectServiceResponse) Reset() {
	*x = InspectServiceResponse{}
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectServiceResponse) ProtoMessage() {}

func (x *InspectServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectServiceResponse.ProtoReflect.Descriptor instead.
func (*InspectServiceResponse) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_machine_proto_rawDescGZIP(), []int{12}
}

func (x *InspectServiceResponse) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

type InspectWireGuardNetworkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterfaceName string                 `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	ListenPort    int32                  `protobuf:"varint,3,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	Peers         []*WireGuardPeer       `protobuf:"bytes,4,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectWireGuardNetworkResponse) Reset() {
	*x = InspectWireGuardNetworkResponse{}
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectWireGuardNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectWireGuardNetworkResponse) ProtoMessage() {}

func (x *InspectWireGuardNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectWireGuardNetworkResponse.ProtoReflect.Descriptor instead.
func (*InspectWireGuardNetworkResponse) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_machine_proto_rawDescGZIP(), []int{13}
}

func (x *InspectWireGuardNetworkResponse) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *InspectWireGuardNetworkResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *InspectWireGuardNetworkResponse) GetListenPort() int32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *InspectWireGuardNetworkResponse) GetPeers() []*WireGuardPeer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type WireGuardPeer struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PublicKey         []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Endpoint          string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	LastHandshakeTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_handshake_time,json=lastHandshakeTime,proto3" json:"last_handshake_time,omitempty"`
	ReceiveBytes      int64                  `protobuf:"varint,4,opt,name=receive_bytes,json=receiveBytes,proto3" json:"receive_bytes,omitempty"`
	TransmitBytes     int64                  `protobuf:"varint,5,opt,name=transmit_bytes,json=transmitBytes,proto3" json:"transmit_bytes,omitempty"`
	AllowedIps        []string               `protobuf:"bytes,6,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WireGuardPeer) Reset() {
	*x = WireGuardPeer{}
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireGuardPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireGuardPeer) ProtoMessage() {}

func (x *WireGuardPeer) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireGuardPeer.ProtoReflect.Descriptor instead.
func (*WireGuardPeer) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_machine_proto_rawDescGZIP(), []int{14}
}

func (x *WireGuardPeer) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *WireGuardPeer) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *WireGuardPeer) GetLastHandshakeTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHandshakeTime
	}
	return nil
}

func (x *WireGuardPeer) GetReceiveBytes() int64 {
	if x != nil {
		return x.ReceiveBytes
	}
	return 0
}

func (x *WireGuardPeer) GetTransmitBytes() int64 {
	if x != nil {
		return x.TransmitBytes
	}
	return 0
}

func (x *WireGuardPeer) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

type LogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Follow        bool                   `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"`
	Tail          int32                  `protobuf:"varint,3,opt,name=tail,proto3" json:"tail,omitempty"`
	Since         string                 `protobuf:"bytes,4,opt,name=since,proto3" json:"since,omitempty"`
	Until         string                 `protobuf:"bytes,5,opt,name=until,proto3" json:"until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_machine_proto_rawDescGZIP(), []int{15}
}

func (x *LogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *LogsRequest) GetTail() int32 {
	if x != nil {
		return x.Tail
	}
	return 0
}

func (x *LogsRequest) GetSince() string {
	if x != nil {
		return x.Since
	}
	return ""
}

func (x *LogsRequest) GetUntil() string {
	if x != nil {
		return x.Until
	}
	return ""
}

// Similar to ContainerLogEntry.
type LogEntry struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Stream    LogEntry_StreamType    `protobuf:"varint,1,opt,name=stream,proto3,enum=api.LogEntry_StreamType" json:"stream,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Log line content. Empty for heartbeat entries.
	Message       []byte `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_machine_proto_rawDescGZIP(), []int{16}
}

func (x *LogEntry) GetStream() LogEntry_StreamType {
	if x != nil {
		return x.Stream
	}
	return LogEntry_UNKNOWN
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEntry) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type Service_Container struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MachineId string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	// JSON encoded Docker types.Container.
	Container     []byte `protobuf:"bytes,2,opt,name=container,proto3" json:"container,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service_Container) Reset() {
	*x = Service_Container{}
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service_Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service_Container) ProtoMessage() {}

func (x *Service_Container) ProtoReflect() protoreflect.Message {
	mi := &file_internal_machine_api_pb_machine_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service_Container.ProtoReflect.Descriptor instead.
func (*Service_Container) Descriptor() ([]byte, []int) {
	return file_internal_machine_api_pb_machine_proto_rawDescGZIP(), []int{10, 0}
}

func (x *Service_Container) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *Service_Container) GetContainer() []byte {
	if x != nil {
		return x.Container
	}
	return nil
}

var File_internal_machine_api_pb_machine_proto protoreflect.FileDescriptor

const file_internal_machine_api_pb_machine_proto_rawDesc = "" +
	"\n" +
	"%internal/machine/api/pb/machine.proto\x12\x03api\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a$internal/machine/api/pb/common.proto\"\x85\x01\n" +
	"\vMachineInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12,\n" +
	"\anetwork\x18\x03 \x01(\v2\x12.api.NetworkConfigR\anetwork\x12$\n" +
	"\tpublic_ip\x18\x04 \x01(\v2\a.api.IPR\bpublicIp\"\xae\x01\n" +
	"\rNetworkConfig\x12%\n" +
	"\x06subnet\x18\x01 \x01(\v2\r.api.IPPrefixR\x06subnet\x12,\n" +
	"\rmanagement_ip\x18\x02 \x01(\v2\a.api.IPR\fmanagementIp\x12)\n" +
	"\tendpoints\x18\x03 \x03(\v2\v.api.IPPortR\tendpoints\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\fR\tpublicKey\"P\n" +
	"\x1aCheckPrerequisitesResponse\x12\x1c\n" +
	"\tsatisfied\x18\x01 \x01(\bR\tsatisfied\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x81\x02\n" +
	"\x12InitClusterRequest\x12 \n" +
	"\vmachineName\x18\x01 \x01(\tR\vmachineName\x12'\n" +
	"\anetwork\x18\x02 \x01(\v2\r.api.IPPrefixR\anetwork\x12&\n" +
	"\tpublic_ip\x18\x03 \x01(\v2\a.api.IPH\x00R\bpublicIp\x12&\n" +
	"\x0epublic_ip_auto\x18\x04 \x01(\bH\x00R\fpublicIpAuto\x12<\n" +
	"\x13wireguard_endpoints\x18\x05 \x03(\v2\v.api.IPPortR\x12wireguardEndpointsB\x12\n" +
	"\x10public_ip_config\"A\n" +
	"\x13InitClusterResponse\x12*\n" +
	"\amachine\x18\x01 \x01(\v2\x10.api.MachineInfoR\amachine\"\xaa\x01\n" +
	"\x12JoinClusterRequest\x12*\n" +
	"\amachine\x18\x01 \x01(\v2\x10.api.MachineInfoR\amachine\x127\n" +
	"\x0eother_machines\x18\x03 \x03(\v2\x10.api.MachineInfoR\rotherMachines\x12/\n" +
	"\x14min_store_db_version\x18\x04 \x01(\x03R\x11minStoreDbVersion\"I\n" +
	"\x16InspectMachineResponse\x12/\n" +
	"\bmachines\x18\x01 \x03(\v2\x13.api.MachineDetailsR\bmachines\"\x91\x01\n" +
	"\x0eMachineDetails\x12)\n" +
	"\bmetadata\x18\x01 \x01(\v2\r.api.MetadataR\bmetadata\x12*\n" +
	"\amachine\x18\x02 \x01(\v2\x10.api.MachineInfoR\amachine\x12(\n" +
	"\x10store_db_version\x18\x03 \x01(\x03R\x0estoreDbVersion\"%\n" +
	"\rTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x0e\n" +
	"\fResetRequest\"\xc3\x01\n" +
	"\aService\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x126\n" +
	"\n" +
	"containers\x18\x04 \x03(\v2\x16.api.Service.ContainerR\n" +
	"containers\x1aH\n" +
	"\tContainer\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12\x1c\n" +
	"\tcontainer\x18\x02 \x01(\fR\tcontainer\"'\n" +
	"\x15InspectServiceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x16InspectServiceResponse\x12&\n" +
	"\aservice\x18\x01 \x01(\v2\f.api.ServiceR\aservice\"\xb2\x01\n" +
	"\x1fInspectWireGuardNetworkResponse\x12%\n" +
	"\x0einterface_name\x18\x01 \x01(\tR\rinterfaceName\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12\x1f\n" +
	"\vlisten_port\x18\x03 \x01(\x05R\n" +
	"listenPort\x12(\n" +
	"\x05peers\x18\x04 \x03(\v2\x12.api.WireGuardPeerR\x05peers\"\x83\x02\n" +
	"\rWireGuardPeer\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12J\n" +
	"\x13last_handshake_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x11lastHandshakeTime\x12#\n" +
	"\rreceive_bytes\x18\x04 \x01(\x03R\freceiveBytes\x12%\n" +
	"\x0etransmit_bytes\x18\x05 \x01(\x03R\rtransmitBytes\x12\x1f\n" +
	"\vallowed_ips\x18\x06 \x03(\tR\n" +
	"allowedIps\"\x98\x01\n" +
	"\vLogsRequest\x12\x16\n" +
	"\x06follow\x18\x02 \x01(\bR\x06follow\x12\x12\n" +
	"\x04tail\x18\x03 \x01(\x05R\x04tail\x12\x14\n" +
	"\x05since\x18\x04 \x01(\tR\x05since\x12\x14\n" +
	"\x05until\x18\x05 \x01(\tR\x05until\"1\n" +
	"\aservice\x12\v\n" +
	"\aUNCLOUD\x10\x00\x12\n" +
	"\n" +
	"\x06DOCKER\x10\x01\x12\r\n" +
	"\tCORROSION\x10\x02\"\xd2\x01\n" +
	"\bLogEntry\x120\n" +
	"\x06stream\x18\x01 \x01(\x0e2\x18.api.LogEntry.StreamTypeR\x06stream\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\amessage\x18\x03 \x01(\fR\amessage\"@\n" +
	"\n" +
	"StreamType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x01\x12\n" +
	"\n" +
	"\x06STDERR\x10\x02\x12\r\n" +
	"\tHEARTBEAT\x10\x032\x8d\x05\n" +
	"\aMachine\x12M\n" +
	"\x12CheckPrerequisites\x12\x16.google.protobuf.Empty\x1a\x1f.api.CheckPrerequisitesResponse\x12@\n" +
	"\vInitCluster\x12\x17.api.InitClusterRequest\x1a\x18.api.InitClusterResponse\x12>\n" +
	"\vJoinCluster\x12\x17.api.JoinClusterRequest\x1a\x16.google.protobuf.Empty\x123\n" +
	"\x05Token\x12\x16.google.protobuf.Empty\x1a\x12.api.TokenResponse\x123\n" +
	"\aInspect\x12\x16.google.protobuf.Empty\x1a\x10.api.MachineInfo\x12E\n" +
	"\x0eInspectMachine\x12\x16.google.protobuf.Empty\x1a\x1b.api.InspectMachineResponse\x12W\n" +
	"\x17InspectWireGuardNetwork\x12\x16.google.protobuf.Empty\x1a$.api.InspectWireGuardNetworkResponse\x122\n" +
	"\x05Reset\x12\x11.api.ResetRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\x0eInspectService\x12\x1a.api.InspectServiceRequest\x1a\x1b.api.InspectServiceResponse\x12(\n" +
	"\x03Log\x12\x10.api.LogsRequest\x1a\r.api.LogEntry0\x01B7Z5github.com/psviderski/uncloud/internal/machine/api/pbb\x06proto3"

var (
	file_internal_machine_api_pb_machine_proto_rawDescOnce sync.Once
	file_internal_machine_api_pb_machine_proto_rawDescData []byte
)

func file_internal_machine_api_pb_machine_proto_rawDescGZIP() []byte {
	file_internal_machine_api_pb_machine_proto_rawDescOnce.Do(func() {
		file_internal_machine_api_pb_machine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_machine_api_pb_machine_proto_rawDesc), len(file_internal_machine_api_pb_machine_proto_rawDesc)))
	})
	return file_internal_machine_api_pb_machine_proto_rawDescData
}

var file_internal_machine_api_pb_machine_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_machine_api_pb_machine_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_internal_machine_api_pb_machine_proto_goTypes = []any{
	(LogsRequestService)(0),                 // 0: api.LogsRequest.service
	(LogEntry_StreamType)(0),                // 1: api.LogEntry.StreamType
	(*MachineInfo)(nil),                     // 2: api.MachineInfo
	(*NetworkConfig)(nil),                   // 3: api.NetworkConfig
	(*CheckPrerequisitesResponse)(nil),      // 4: api.CheckPrerequisitesResponse
	(*InitClusterRequest)(nil),              // 5: api.InitClusterRequest
	(*InitClusterResponse)(nil),             // 6: api.InitClusterResponse
	(*JoinClusterRequest)(nil),              // 7: api.JoinClusterRequest
	(*InspectMachineResponse)(nil),          // 8: api.InspectMachineResponse
	(*MachineDetails)(nil),                  // 9: api.MachineDetails
	(*TokenResponse)(nil),                   // 10: api.TokenResponse
	(*ResetRequest)(nil),                    // 11: api.ResetRequest
	(*Service)(nil),                         // 12: api.Service
	(*InspectServiceRequest)(nil),           // 13: api.InspectServiceRequest
	(*InspectServiceResponse)(nil),          // 14: api.InspectServiceResponse
	(*InspectWireGuardNetworkResponse)(nil), // 15: api.InspectWireGuardNetworkResponse
	(*WireGuardPeer)(nil),                   // 16: api.WireGuardPeer
	(*LogsRequest)(nil),                     // 17: api.LogsRequest
	(*LogEntry)(nil),                        // 18: api.LogEntry
	(*Service_Container)(nil),               // 19: api.Service.Container
	(*IP)(nil),                              // 20: api.IP
	(*IPPrefix)(nil),                        // 21: api.IPPrefix
	(*IPPort)(nil),                          // 22: api.IPPort
	(*Metadata)(nil),                        // 23: api.Metadata
	(*timestamppb.Timestamp)(nil),           // 24: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                   // 25: google.protobuf.Empty
}
var file_internal_machine_api_pb_machine_proto_depIdxs = []int32{
	3,  // 0: api.MachineInfo.network:type_name -> api.NetworkConfig
	20, // 1: api.MachineInfo.public_ip:type_name -> api.IP
	21, // 2: api.NetworkConfig.subnet:type_name -> api.IPPrefix
	20, // 3: api.NetworkConfig.management_ip:type_name -> api.IP
	22, // 4: api.NetworkConfig.endpoints:type_name -> api.IPPort
	21, // 5: api.InitClusterRequest.network:type_name -> api.IPPrefix
	20, // 6: api.InitClusterRequest.public_ip:type_name -> api.IP
	22, // 7: api.InitClusterRequest.wireguard_endpoints:type_name -> api.IPPort
	2,  // 8: api.InitClusterResponse.machine:type_name -> api.MachineInfo
	2,  // 9: api.JoinClusterRequest.machine:type_name -> api.MachineInfo
	2,  // 10: api.JoinClusterRequest.other_machines:type_name -> api.MachineInfo
	9,  // 11: api.InspectMachineResponse.machines:type_name -> api.MachineDetails
	23, // 12: api.MachineDetails.metadata:type_name -> api.Metadata
	2,  // 13: api.MachineDetails.machine:type_name -> api.MachineInfo
	19, // 14: api.Service.containers:type_name -> api.Service.Container
	12, // 15: api.InspectServiceResponse.service:type_name -> api.Service
	16, // 16: api.InspectWireGuardNetworkResponse.peers:type_name -> api.WireGuardPeer
	24, // 17: api.WireGuardPeer.last_handshake_time:type_name -> google.protobuf.Timestamp
	1,  // 18: api.LogEntry.stream:type_name -> api.LogEntry.StreamType
	24, // 19: api.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	25, // 20: api.Machine.CheckPrerequisites:input_type -> google.protobuf.Empty
	5,  // 21: api.Machine.InitCluster:input_type -> api.InitClusterRequest
	7,  // 22: api.Machine.JoinCluster:input_type -> api.JoinClusterRequest
	25, // 23: api.Machine.Token:input_type -> google.protobuf.Empty
	25, // 24: api.Machine.Inspect:input_type -> google.protobuf.Empty
	25, // 25: api.Machine.InspectMachine:input_type -> google.protobuf.Empty
	25, // 26: api.Machine.InspectWireGuardNetwork:input_type -> google.protobuf.Empty
	11, // 27: api.Machine.Reset:input_type -> api.ResetRequest
	13, // 28: api.Machine.InspectService:input_type -> api.InspectServiceRequest
	17, // 29: api.Machine.Log:input_type -> api.LogsRequest
	4,  // 30: api.Machine.CheckPrerequisites:output_type -> api.CheckPrerequisitesResponse
	6,  // 31: api.Machine.InitCluster:output_type -> api.InitClusterResponse
	25, // 32: api.Machine.JoinCluster:output_type -> google.protobuf.Empty
	10, // 33: api.Machine.Token:output_type -> api.TokenResponse
	2,  // 34: api.Machine.Inspect:output_type -> api.MachineInfo
	8,  // 35: api.Machine.InspectMachine:output_type -> api.InspectMachineResponse
	15, // 36: api.Machine.InspectWireGuardNetwork:output_type -> api.InspectWireGuardNetworkResponse
	25, // 37: api.Machine.Reset:output_type -> google.protobuf.Empty
	14, // 38: api.Machine.InspectService:output_type -> api.InspectServiceResponse
	18, // 39: api.Machine.Log:output_type -> api.LogEntry
	30, // [30:40] is the sub-list for method output_type
	20, // [20:30] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_internal_machine_api_pb_machine_proto_init() }
func file_internal_machine_api_pb_machine_proto_init() {
	if File_internal_machine_api_pb_machine_proto != nil {
		return
	}
	file_internal_machine_api_pb_common_proto_init()
	file_internal_machine_api_pb_machine_proto_msgTypes[3].OneofWrappers = []any{
		(*InitClusterRequest_PublicIp)(nil),
		(*InitClusterRequest_PublicIpAuto)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_machine_api_pb_machine_proto_rawDesc), len(file_internal_machine_api_pb_machine_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_machine_api_pb_machine_proto_goTypes,
		DependencyIndexes: file_internal_machine_api_pb_machine_proto_depIdxs,
		EnumInfos:         file_internal_machine_api_pb_machine_proto_enumTypes,
		MessageInfos:      file_internal_machine_api_pb_machine_proto_msgTypes,
	}.Build()
	File_internal_machine_api_pb_machine_proto = out.File
	file_internal_machine_api_pb_machine_proto_goTypes = nil
	file_internal_machine_api_pb_machine_proto_depIdxs = nil
}
