name: Lint
on:
  push:
    branches:
      - "main"
      - "test/**"
      - "release/**"
  pull_request:
    branches:
      - main
    paths:
      - "**.go"
      - "go.*"
permissions:
  contents: read
env:
  MISE_VERSION: "2026.3.7"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Mise
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        with:
          version: ${{ env.MISE_VERSION }}
      - name: Reset changes in mise.lock after fresh mise install
        run: git checkout mise.lock

      - name: Lint
        run: make lint

    timeout-minutes: 10
